#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 `.aidp/` 单一信源装配成 Claude Code、Codex 与 DeepSeek Harness 的项目入口。

目录契约：

| Agent | 公共 SKILL | 命令入口 | chrome-devtools-mcp |
|-------|------------|----------|---------------------|
| Claude Code | `.claude/skills/` | `.claude/commands/*.md` | `.claude/plugins/<name>/` |
| Codex | `.agents/skills/` | `.codex/skills/aidp/<command>/SKILL.md` | `.codex/skills/<name>/skills/` + `.codex/config.toml` MCP |
| DeepSeek Harness | `.agents/skills/` | `.dsh/commands/*.md` | 插件 SKILL 合并进 `.agents/skills/` + `.dsh/mcp.json` |

`.aidp/commands/`、`.aidp/skills/`、`.aidp/plugins/` 始终是唯一真源。生成入口使用相对符号链接，
或在 `--mode copy` 下生成带标记的副本；只清理由本脚本生成的内容，保留用户自有配置和入口。
Codex 命令逐条生成显式调用 SKILL，DSH 由 `dsh-plugin-commands` 读取原生命令文件。

用法：

    python3 .aidp/scripts/agent_sync.py
    python3 .aidp/scripts/agent_sync.py --agents claude,codex,dsh
    python3 .aidp/scripts/agent_sync.py --mode copy
    python3 .aidp/scripts/agent_sync.py --check
    python3 .aidp/scripts/agent_sync.py --self-check

stdout 恒为一行 JSON（`--human` 另输出人读摘要到 stderr）。
退出码：0 = 已一致 / 已写入；1 = `--check` 发现漂移；2 = 参数或环境错误。
"""
import argparse
import json
import os
import re
import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from agent_env import detect_agents, KNOWN_AGENTS  # noqa: E402

AIDP_DIR = ".aidp"
SHELL_BODY = "@AGENTS.md\n"
STOP_GUARD_REL = ".aidp/hooks/autopilot-stop-guard.py"
GENERATED_MARK = "<!-- generated by .aidp/scripts/agent_sync.py; edit .aidp/commands instead -->"
GENERATED_FILE = ".aidp-generated"
OBSOLETE_ROUTER = "aidp-cmd"

CLAUDE_SKILLS = ".claude/skills"
SHARED_SKILLS = ".agents/skills"
CLAUDE_COMMANDS = ".claude/commands"
CODEX_COMMAND_SKILLS = ".codex/skills/aidp"
LEGACY_CODEX_COMMAND_SKILLS = ".codex/aidp/skills"
DSH_COMMANDS = ".dsh/commands"
PLUGINS_SRC = "plugins"
CLAUDE_PLUGINS = ".claude/plugins"
CODEX_PLUGIN_SKILLS = ".codex/skills"
OPENAI_YAML = "policy:\n  allow_implicit_invocation: false\n"
CODEX_BODY_MARKER = "## 原始命令正文（逐字保真）\n\n"
CODEX_MCP_BEGIN = "# >>> AIDP-MCP {name} >>>"
CODEX_MCP_END = "# <<< AIDP-MCP {name} <<<"
DSH_MCP_MANAGED = ".dsh/.aidp-mcp-servers.json"
CLAUDE_PLUGIN_MANAGED = ".claude/.aidp-plugins.json"
LEGACY_CODEX_PLUGINS = ".agents/plugins"
CODEX_MCP_SUPPORTED_FIELDS = {
    "command", "args", "url", "enabled", "startup_timeout_sec", "tool_timeout_sec",
}
GITIGNORE_BEGIN = "# >>> AIDP-AGENT-ADAPTERS（由 .aidp/scripts/agent_sync.py 生成，勿手改）>>>"
GITIGNORE_END = "# <<< AIDP-AGENT-ADAPTERS <<<"
CODEX_HOOK_LINE_RE = re.compile(
    r"(?m)^(?P<indent>[ \t]*)codex_hooks(?P<before>[ \t]*)="
    r"(?P<after>[ \t]*)(?P<value>true|false)(?P<comment>[ \t]*(?:#.*)?)$"
)


# ── 通用小工具 ────────────────────────────────────────────────────────────────
def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""


def _frontmatter(text: str) -> dict:
    """只解析 `key: value` 单行形式，够读 description / argument-hint。"""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    out = {}
    if not m:
        return out
    for line in m.group(1).splitlines():
        kv = re.match(r"^([A-Za-z_-]+)\s*:\s*(.*)$", line)
        if kv:
            out[kv.group(1)] = kv.group(2).strip().strip('"').strip("'")
    return out


def _title_description(text: str) -> str:
    """命令文件无 frontmatter 时，取首个 H1「# /name — 说明」里破折号后的说明（去掉标题装饰符 ★）。"""
    m = re.search(r"^#\s+/?[\w-]+\s*[—-]+\s*(.+?)\s*$", text, re.M)
    if not m:
        return ""
    desc = re.sub(r"[（(]\s*★\s*[)）]|★", "", m.group(1)).strip()
    return f"AIDP 命令：{desc}"


def _is_shell(text: str) -> bool:
    body = [l for l in text.splitlines() if l.strip() and not l.strip().startswith("<!--")]
    return len(body) == 1 and body[0].strip() == "@AGENTS.md"


class Plan:
    """收集动作；apply=False 时只记录不落盘。"""

    def __init__(self, root: Path, apply: bool, mode: str):
        self.root, self.apply, self.mode = root, apply, mode
        self.actions = []

    def _rel(self, p: Path) -> str:
        return p.relative_to(self.root).as_posix()

    def write_text(self, p: Path, text: str):
        if _read(p) == text and p.is_file() and not p.is_symlink():
            return
        self.actions.append({"op": "write", "path": self._rel(p)})
        if self.apply:
            if p.is_symlink():
                p.unlink()
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")

    def link_dir(self, dst: Path, src: Path):
        """dst 指向 src（目录）。link 模式建相对符号链接；copy 模式整目录镜像。"""
        if self.mode == "link":
            target = os.path.relpath(src, dst.parent)
            if dst.is_symlink() and os.readlink(dst) == target:
                return
            self.actions.append({"op": "link", "path": self._rel(dst), "target": target})
            if self.apply:
                self._remove(dst)
                dst.parent.mkdir(parents=True, exist_ok=True)
                os.symlink(target, dst, target_is_directory=True)
        else:
            if dst.is_dir() and not dst.is_symlink() and _tree_equal(src, dst):
                return
            self.actions.append({"op": "copy", "path": self._rel(dst), "from": self._rel(src)})
            if self.apply:
                self._remove(dst)
                shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
                (dst / GENERATED_FILE).write_text("directory-copy\n", encoding="utf-8")

    def link_file(self, dst: Path, src: Path):
        if self.mode == "link":
            target = os.path.relpath(src, dst.parent)
            if dst.is_symlink() and os.readlink(dst) == target:
                return
            self.actions.append({"op": "link", "path": self._rel(dst), "target": target})
            if self.apply:
                self._remove(dst)
                dst.parent.mkdir(parents=True, exist_ok=True)
                os.symlink(target, dst)
        else:
            if dst.is_file() and not dst.is_symlink() and dst.read_bytes() == src.read_bytes():
                return
            self.actions.append({"op": "copy", "path": self._rel(dst), "from": self._rel(src)})
            if self.apply:
                self._remove(dst)
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(src, dst)

    def remove(self, p: Path, why: str):
        if not (p.exists() or p.is_symlink()):
            return
        self.actions.append({"op": "remove", "path": self._rel(p), "why": why})
        if self.apply:
            self._remove(p)

    @staticmethod
    def _remove(p: Path):
        if p.is_symlink() or p.is_file():
            p.unlink()
        elif p.is_dir():
            shutil.rmtree(p)


def _tree_equal(a: Path, b: Path) -> bool:
    def files(base):
        return {f.relative_to(base).as_posix(): f for f in base.rglob("*")
                if f.is_file() and "__pycache__" not in f.parts and f.suffix != ".pyc"
                and f.name != GENERATED_FILE}
    fa, fb = files(a), files(b)
    if fa.keys() != fb.keys():
        return False
    return all(fa[k].read_bytes() == fb[k].read_bytes() for k in fa)


# ── 记忆文件 ──────────────────────────────────────────────────────────────────
def sync_memory(plan: Plan, agents: list):
    root = plan.root
    agents_md, claude_md = root / "AGENTS.md", root / "CLAUDE.md"
    a_txt, c_txt = _read(agents_md), _read(claude_md)
    c_body = c_txt if (c_txt and not _is_shell(c_txt)) else ""
    a_body = a_txt if (a_txt and not _is_shell(a_txt)) else ""
    only_claude = agents == ["claude"]

    if only_claude:
        if c_body:
            return  # 正文已在 CLAUDE.md
        if a_body:
            # 正文在 AGENTS.md：保持单一正文，CLAUDE.md 做导入薄壳（Claude Code 读 CLAUDE.md）
            plan.write_text(claude_md, SHELL_BODY)
        return

    # 存在非 Claude Agent：正文必须在 AGENTS.md
    if not a_body and c_body:
        plan.write_text(agents_md, c_body)  # 搬正文，⛔ 不丢
        a_body = c_body
    if "claude" in agents and a_body:
        plan.write_text(claude_md, SHELL_BODY)


# ── 原生命令与 SKILL 入口 ────────────────────────────────────────────────────
def _command_files(root: Path) -> list:
    src = root / AIDP_DIR / "commands"
    if not src.is_dir():
        return []
    return [p for p in sorted(src.glob("*.md")) if p.stem.upper() != "README"]


def _command_description(name: str, text: str) -> str:
    frontmatter = _frontmatter(text)
    if frontmatter.get("description"):
        return frontmatter["description"].replace('"', "'")
    match = re.search(r"^#\s+(.+?)\s*$", text, re.M)
    return (match.group(1).strip() if match else f"AIDP command {name}").replace('"', "'")


def _codex_command_preamble(name: str) -> str:
    return (
        "## Codex 命令适配规则\n\n"
        f"1. 用户以 `${name} args` 调用本命令时，`args` 的全部文字原样作为本命令的 `$ARGUMENTS`；"
        "不增删、不改写、不调整顺序与引号。\n"
        "2. 当下方原始命令正文明确调用或串联 `/foo args` 时，不依赖隐式 SKILL 调用，而是读取 "
        "`.aidp/commands/<命令名>.md`（此处命令名为 `foo`）。确认文件存在后，将 `args` 原样作为"
        "子命令的 `$ARGUMENTS`，在当前执行链内联执行。\n"
        "3. 被引用的命令文件不存在、命令名未知或无法唯一映射时，必须 fail closed：停止执行并报告未知命令，严禁猜测或跳过。\n"
        "4. 本适配层只负责参数传递和命令串联；不得改写下方原始命令正文。\n\n"
    )


def codex_command_skill(name: str, command_text: str) -> str:
    return (
        "---\n"
        f"name: {name}\n"
        f'description: "{_command_description(name, command_text)}"\n'
        "disable-model-invocation: true\n"
        "user-invocable: true\n"
        "---\n\n"
        f"{_codex_command_preamble(name)}"
        f"{CODEX_BODY_MARKER}"
        f"{command_text}"
    )


def _is_generated(p: Path) -> bool:
    if p.is_symlink():
        return AIDP_DIR in os.readlink(p)
    if p.is_dir():
        skill_text = _read(p / "SKILL.md")
        return ((p / GENERATED_FILE).is_file() or GENERATED_MARK in skill_text
                or "命令表由 .aidp/scripts/agent_sync.py" in skill_text)
    return GENERATED_MARK in _read(p) or (p.name == "marketplace.json" and _read(p.parent / GENERATED_FILE) == "marketplace\n")


def _prune(plan: Plan, base: Path, wanted: set):
    """只遍历 root 内无 symlink 祖先的真实目录，绝不跨越适配边界。"""
    try:
        relative = base.relative_to(plan.root)
    except ValueError:
        return
    current = plan.root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            return
    if not base.is_dir():
        return
    for p in sorted(base.iterdir()):
        if p.name not in wanted and _is_generated(p):
            plan.remove(p, "not generated anymore")


def _require_generated_or_absent(path: Path, label: str):
    if (path.exists() or path.is_symlink()) and not _is_generated(path):
        raise SystemExit(f"[agent_sync] {label} 已存在用户内容，拒绝覆盖：{path}")


def _base_skill_dirs(root: Path) -> dict:
    source = root / AIDP_DIR / "skills"
    if not source.is_dir():
        return {}
    return {p.name: p for p in sorted(source.iterdir())
            if p.name != OBSOLETE_ROUTER and (p / "SKILL.md").is_file()}


def sync_skill_dir(plan: Plan, rel: str, extra: dict = None) -> list:
    skills = _base_skill_dirs(plan.root)
    for name, source in (extra or {}).items():
        if name in skills:
            raise SystemExit(f"[agent_sync] 插件 SKILL 与公共 SKILL 同名冲突：{name}")
        skills[name] = source
    generated = []
    destination = plan.root / rel
    for name, source in sorted(skills.items()):
        target = destination / name
        _require_generated_or_absent(target, "SKILL 入口")
        plan.link_dir(target, source)
        generated.append(f"{rel}/{name}")
    _prune(plan, destination, set(skills))
    return generated


def _generated_names(path: Path) -> set:
    try:
        data = json.loads(_read(path) or "[]")
    except json.JSONDecodeError:
        return set()
    return {str(item) for item in data if isinstance(item, str)} if isinstance(data, list) else set()


def sync_file_commands(plan: Plan, rel: str, enabled: bool = True) -> list:
    destination = plan.root / rel
    marker = destination / GENERATED_FILE
    previous = _generated_names(marker)
    commands = _command_files(plan.root) if enabled else []
    wanted = {command.name for command in commands}
    for name in sorted(previous - wanted):
        plan.remove(destination / name, "command source removed")
    generated = []
    for command in commands:
        target = destination / command.name
        if (target.exists() or target.is_symlink()) and command.name not in previous and not _is_generated(target):
            raise SystemExit(f"[agent_sync] 原生命令目标已存在用户内容，拒绝覆盖：{target}")
        plan.link_file(target, command)
        generated.append(f"{rel}/{command.name}")
    if wanted:
        plan.write_text(marker, json.dumps(sorted(wanted), ensure_ascii=False) + "\n")
        generated.append(f"{rel}/{GENERATED_FILE}")
    elif marker.is_file():
        plan.remove(marker, "no generated commands")
    return generated


def sync_codex_commands(plan: Plan) -> list:
    destination = plan.root / CODEX_COMMAND_SKILLS
    wanted = set()
    generated = []
    for command in _command_files(plan.root):
        name = command.stem
        target = destination / name
        _require_generated_or_absent(target, "Codex 命令 SKILL")
        wanted.add(name)
        plan.write_text(target / "SKILL.md", codex_command_skill(name, _read(command)))
        plan.write_text(target / "agents/openai.yaml", OPENAI_YAML)
        plan.write_text(target / GENERATED_FILE, "native-command\n")
        generated.append(f"{CODEX_COMMAND_SKILLS}/{name}")
    _prune(plan, destination, wanted)
    return generated


def _covered_by_dir_rules(text_outside: str, entry: str) -> bool:
    """entry（仓库相对路径）是否已被块外的锚定目录规则（如 `/.claude/`）整体忽略。"""
    for line in text_outside.splitlines():
        rule = line.strip()
        if not rule or rule.startswith(("#", "!")) or not rule.endswith("/") or any(c in rule for c in "*?["):
            continue
        prefix = rule.lstrip("/")
        if entry == prefix.rstrip("/") or entry.startswith(prefix):
            return True
    return False


def sync_gitignore(plan: Plan, generated: list):
    """根 .gitignore 托管块：列出全部生成物（块外目录规则已覆盖的不重复登记）；块外内容原样保留。"""
    path = plan.root / ".gitignore"
    text = _read(path)
    block_re = re.compile(re.escape(GITIGNORE_BEGIN) + r".*?" + re.escape(GITIGNORE_END) + r"\n?", re.S)
    outside = block_re.sub("", text)
    generated = [g for g in generated if not _covered_by_dir_rules(outside, g)]
    body = "".join(f"/{g}\n" for g in sorted(set(generated)))
    block = f"{GITIGNORE_BEGIN}\n{body}{GITIGNORE_END}\n" if generated else ""
    if block_re.search(text):
        new = block_re.sub(lambda _m: block, text)
        if not block:
            new = new.rstrip("\n") + "\n" if new.strip() else ""
    elif block:
        new = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
    else:
        new = text
    if new != text:
        plan.write_text(path, new)


# ── 插件（`.aidp/plugins/<name>/`：随仓库分发，含 MCP 声明与配套 SKILL）──────────
def _plugin_dirs(root: Path) -> list:
    base = root / AIDP_DIR / PLUGINS_SRC
    if not base.is_dir():
        return []
    return sorted(p for p in base.iterdir()
                  if p.is_dir() and ((p / ".claude-plugin" / "plugin.json").is_file()
                                     or (p / "plugin.json").is_file()))


def _plugin_manifest(pdir: Path) -> dict:
    for rel in (".claude-plugin/plugin.json", "plugin.json"):
        try:
            return json.loads(_read(pdir / rel) or "{}")
        except json.JSONDecodeError:
            raise SystemExit(f"[agent_sync] {pdir / rel} 不是合法 JSON")
    return {}


def _plugin_mcp(pdir: Path, manifest: dict) -> dict:
    """插件声明的 MCP servers：根 `.mcp.json` / `mcp.json` 优先，其次 manifest 内联。"""
    for rel in (".mcp.json", "mcp.json"):
        if (pdir / rel).is_file():
            try:
                return (json.loads(_read(pdir / rel)) or {}).get("mcpServers") or {}
            except json.JSONDecodeError:
                raise SystemExit(f"[agent_sync] {pdir / rel} 不是合法 JSON")
    return manifest.get("mcpServers") or {}


def sync_claude_plugins(plan: Plan, plugins: list) -> list:
    """Claude Code 项目插件；settings 只增删 marker 明确记录的键。"""
    root, generated = plan.root, []
    for plugin in plugins:
        name = plugin.name
        plan.link_dir(root / CLAUDE_PLUGINS / name, plugin)
        generated.append(f"{CLAUDE_PLUGINS}/{name}")
    _prune(plan, root / CLAUDE_PLUGINS, {plugin.name for plugin in plugins})

    path = root / ".claude/settings.json"
    marker = root / CLAUDE_PLUGIN_MANAGED
    if not plugins and not marker.is_file():
        return generated
    try:
        data = json.loads(_read(path) or "{}")
        previous = json.loads(_read(marker) or "{}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"[agent_sync] Claude 插件配置不是合法 JSON：{exc}")
    markets = data.setdefault("extraKnownMarketplaces", {})
    enabled = data.setdefault("enabledPlugins", {})
    for key in previous.get("marketplaces", []):
        markets.pop(key, None)
    for key in previous.get("enabledPlugins", []):
        enabled.pop(key, None)

    managed_markets = []
    managed_enabled = []
    for plugin in plugins:
        marketplace_file = plugin / ".claude-plugin/marketplace.json"
        marketplace = json.loads(_read(marketplace_file) or "{}") if marketplace_file.is_file() else {}
        market = marketplace.get("name") or f"{plugin.name}-marketplace"
        desired_market = {"source": {"source": "directory", "path": f"./{CLAUDE_PLUGINS}/{plugin.name}"}}
        if market in markets and markets[market] != desired_market:
            raise SystemExit(f"[agent_sync] Claude marketplace 用户配置冲突：{market}")
        if market not in markets:
            markets[market] = desired_market
            managed_markets.append(market)
        for entry in marketplace.get("plugins") or [{"name": plugin.name}]:
            key = f"{entry.get('name', plugin.name)}@{market}"
            if key in enabled and enabled[key] is not True:
                raise SystemExit(f"[agent_sync] Claude enabledPlugins 用户配置冲突：{key}")
            if key not in enabled:
                enabled[key] = True
                managed_enabled.append(key)

    if not markets:
        data.pop("extraKnownMarketplaces", None)
    if not enabled:
        data.pop("enabledPlugins", None)
    plan.write_text(path, _json_dump(data))
    managed = {"marketplaces": managed_markets, "enabledPlugins": managed_enabled}
    if managed_markets or managed_enabled:
        plan.write_text(marker, _json_dump(managed))
        generated.append(CLAUDE_PLUGIN_MANAGED)
    elif marker.is_file():
        plan.remove(marker, "no managed Claude plugin settings")
    return generated


def _plugin_skill_dirs(plugins: list) -> dict:
    result = {}
    for plugin in plugins:
        source = plugin / "skills"
        if not source.is_dir():
            continue
        for skill in sorted(source.iterdir()):
            if not (skill / "SKILL.md").is_file():
                continue
            if skill.name in result:
                raise SystemExit(f"[agent_sync] 插件 SKILL 重名冲突：{skill.name}")
            result[skill.name] = skill
    return result


def _plugin_servers(plugins: list) -> dict:
    servers = {}
    for plugin in plugins:
        for name, config in _plugin_mcp(plugin, _plugin_manifest(plugin)).items():
            if name in servers and servers[name] != config:
                raise SystemExit(f"[agent_sync] 插件 MCP server 重名冲突：{name}")
            servers[name] = config
    return servers


def sync_codex_plugin_skills(plan: Plan, plugins: list) -> list:
    base = plan.root / CODEX_PLUGIN_SKILLS
    wanted = set()
    generated = []
    for plugin in plugins:
        source = plugin / "skills"
        if not source.is_dir():
            continue
        wanted.add(plugin.name)
        target = base / plugin.name
        _require_generated_or_absent(target, "Codex 插件 SKILL 目录")
        plan.link_dir(target / "skills", source)
        plan.write_text(target / GENERATED_FILE, "plugin-skills\n")
        generated.append(f"{CODEX_PLUGIN_SKILLS}/{plugin.name}")
    _prune(plan, base, wanted)
    return generated


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    return json.dumps(str(value), ensure_ascii=False)


def _codex_mcp_block(name: str, config: dict) -> str:
    lines = [CODEX_MCP_BEGIN.format(name=name), f"[mcp_servers.{name}]"]
    for key in ("command", "args", "url", "enabled", "startup_timeout_sec", "tool_timeout_sec"):
        if key in config:
            lines.append(f"{key} = {_toml_value(config[key])}")
    lines.append(CODEX_MCP_END.format(name=name))
    return "\n".join(lines) + "\n"


def _toml_scalar(raw: str):
    raw = raw.strip()
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return raw.strip('"').strip("'")


def _toml_section(text: str, header: str):
    match = re.search(rf"(?m)^\[{re.escape(header)}\]\s*$", text)
    if not match:
        return None
    next_header = re.search(r"(?m)^\[", text[match.end():])
    end = match.end() + next_header.start() if next_header else len(text)
    values = {}
    for line in text[match.end():end].splitlines():
        item = re.match(r"^\s*([A-Za-z0-9_-]+)\s*=\s*(.*?)\s*$", line)
        if item:
            values[item.group(1)] = _toml_scalar(item.group(2))
    return values


def _mcp_matches(existing: dict, desired: dict) -> bool:
    return all(existing.get(key) == value for key, value in desired.items())


def _without_codex_managed_mcp(text: str) -> str:
    return re.sub(r"(?ms)^# >>> AIDP-MCP [^\n]+ >>>\n.*?^# <<< AIDP-MCP [^\n]+ <<<\n?", "", text)


def _validate_codex_mcp(root: Path, servers: dict):
    text = _without_codex_managed_mcp(_read(root / ".codex/config.toml"))
    for name, config in sorted(servers.items()):
        if not isinstance(config, dict):
            raise SystemExit(f"[agent_sync] Codex MCP server {name} 配置必须是对象")
        unsupported = sorted(set(config) - CODEX_MCP_SUPPORTED_FIELDS)
        if unsupported:
            raise SystemExit(
                f"[agent_sync] Codex MCP server {name} 含未支持字段：{', '.join(unsupported)}")
        existing = _toml_section(text, f"mcp_servers.{name}")
        if existing is not None and not _mcp_matches(existing, config):
            raise SystemExit(f"[agent_sync] Codex 未受管 MCP server 配置冲突：{name}")


def sync_codex_mcp(plan: Plan, servers: dict, legacy_plugins: set):
    path = plan.root / ".codex/config.toml"
    original = _read(path)
    text = _without_codex_managed_mcp(original)
    for plugin_name in sorted(legacy_plugins):
        pattern = (rf'(?ms)^\[plugins\."{re.escape(plugin_name)}@local-repo"\]\s*\n'
                   r'.*?(?=^\[|\Z)')
        text = re.sub(pattern, "", text)

    managed_servers = {}
    for name, config in sorted(servers.items()):
        existing = _toml_section(text, f"mcp_servers.{name}")
        if existing is None:
            managed_servers[name] = config
        elif not _mcp_matches(existing, config):
            raise SystemExit(f"[agent_sync] Codex 未受管 MCP server 配置冲突：{name}")

    text = text.rstrip()
    blocks = "\n".join(_codex_mcp_block(name, config).rstrip()
                       for name, config in sorted(managed_servers.items()))
    if blocks:
        text = (text + "\n\n" if text else "") + blocks + "\n"
    elif text:
        text += "\n"
    if text != original:
        plan.write_text(path, text)


def _validate_dsh_mcp(root: Path, servers: dict):
    path = root / ".dsh/mcp.json"
    try:
        data = json.loads(_read(path) or "{}")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] {path} 不是合法 JSON，拒绝覆盖，请先修复")
    current = data.get("mcpServers") or {}
    if not isinstance(current, dict):
        raise SystemExit(f"[agent_sync] {path} 的 mcpServers 必须是对象")
    previous = _generated_names(root / DSH_MCP_MANAGED)
    for name, config in servers.items():
        if name in current and name not in previous and current[name] != config:
            raise SystemExit(f"[agent_sync] DSH 未受管 MCP server 配置冲突：{name}")


def sync_dsh_mcp(plan: Plan, servers: dict) -> list:
    root = plan.root
    path = root / ".dsh/mcp.json"
    marker = root / DSH_MCP_MANAGED
    try:
        data = json.loads(_read(path) or "{}")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] {path} 不是合法 JSON，拒绝覆盖，请先修复")
    current = data.get("mcpServers")
    if current is None:
        current = {}
    if not isinstance(current, dict):
        raise SystemExit(f"[agent_sync] {path} 的 mcpServers 必须是对象")

    previous = _generated_names(marker)
    for name in previous:
        current.pop(name, None)
    managed = set()
    for name, config in sorted(servers.items()):
        if name in current:
            if current[name] != config:
                raise SystemExit(f"[agent_sync] DSH 未受管 MCP server 配置冲突：{name}")
            continue
        current[name] = config
        managed.add(name)

    if current:
        data["mcpServers"] = current
    else:
        data.pop("mcpServers", None)
    generated = []
    if data:
        plan.write_text(path, _json_dump(data))
        generated.append(".dsh/mcp.json")
    elif path.is_file():
        plan.remove(path, "no DSH MCP configuration remains")
    if managed:
        plan.write_text(marker, json.dumps(sorted(managed), ensure_ascii=False) + "\n")
        generated.append(DSH_MCP_MANAGED)
    elif marker.is_file():
        plan.remove(marker, "no managed DSH MCP servers")
    return generated


def _legacy_codex_managed(root: Path) -> set:
    base = root / LEGACY_CODEX_PLUGINS
    managed = {path.name for path in base.iterdir()
               if path.is_dir() and (path / GENERATED_FILE).is_file()} if base.is_dir() else set()
    marker = base / GENERATED_FILE
    if _read(marker) == "marketplace\n":
        try:
            marketplace = json.loads(_read(base / "marketplace.json") or "{}")
        except json.JSONDecodeError:
            marketplace = {}
        managed.update(entry.get("name") for entry in marketplace.get("plugins", [])
                       if isinstance(entry, dict) and entry.get("name"))
    return managed


def cleanup_legacy_codex_plugins(plan: Plan) -> set:
    base = plan.root / LEGACY_CODEX_PLUGINS
    managed = _legacy_codex_managed(plan.root)
    marker = base / GENERATED_FILE
    _prune(plan, base, set())
    if _read(marker) == "marketplace\n":
        plan.remove(marker, "legacy marketplace marker")
    return managed


# ── hooks ────────────────────────────────────────────────────────────────────
def _hook_cmd(agent: str) -> str:
    if agent == "claude":
        return f'python3 "$CLAUDE_PROJECT_DIR/{STOP_GUARD_REL}"'
    return f'python3 "$(git rev-parse --show-toplevel)/{STOP_GUARD_REL}" --agent {agent}'


def _merge_stop_hook(data: dict, cmd: str) -> dict:
    hooks = data.setdefault("hooks", {})
    stop = hooks.setdefault("Stop", [])
    for group in stop:
        for h in group.get("hooks", []):
            if STOP_GUARD_REL in h.get("command", ""):
                h["command"] = cmd
                h["type"] = "command"
                return data
    stop.append({"hooks": [{"type": "command", "command": cmd}]})
    return data


def _json_dump(data: dict) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def sync_hooks(plan: Plan, agent: str):
    root = plan.root
    if not (root / STOP_GUARD_REL).is_file():
        return
    path = {"claude": root / ".claude" / "settings.json",
            "codex": root / ".codex" / "hooks.json",
            "dsh": root / ".dsh" / "hooks.json"}[agent]
    try:
        data = json.loads(_read(path) or "{}")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] {path} 不是合法 JSON，拒绝覆盖，请先修复")
    plan.write_text(path, _json_dump(_merge_stop_hook(data, _hook_cmd(agent))))
    if agent == "codex":
        cfg = root / ".codex" / "config.toml"
        text = _read(cfg)
        merged = _merge_codex_hook_flag(text)
        if merged != text:
            plan.write_text(cfg, merged)


# ── 主流程 ────────────────────────────────────────────────────────────────────
def _name_conflicts(root: Path, plugin_skills: dict) -> list:
    skills = set(_base_skill_dirs(root)) | set(plugin_skills)
    commands = {path.stem for path in _command_files(root)}
    return sorted(skills & commands)


def _json_object(path: Path, label: str) -> dict:
    try:
        value = json.loads(_read(path) or "{}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"[agent_sync] {label} JSON 非法：{exc}")
    if not isinstance(value, dict):
        raise SystemExit(f"[agent_sync] {label} 类型错误：顶层必须是对象")
    return value


def _validate_hook_structure(data: dict, path: Path):
    hooks = data.get("hooks", {})
    if not isinstance(hooks, dict):
        raise SystemExit(f"[agent_sync] hooks 结构错误：{path} 的 hooks 必须是对象")
    stop = hooks.get("Stop", [])
    if not isinstance(stop, list):
        raise SystemExit(f"[agent_sync] hooks 结构错误：{path} 的 Stop 必须是数组")
    for index, group in enumerate(stop):
        if not isinstance(group, dict):
            raise SystemExit(f"[agent_sync] hooks 结构错误：{path} Stop[{index}] 必须是对象")
        entries = group.get("hooks", [])
        if not isinstance(entries, list):
            raise SystemExit(f"[agent_sync] hooks 结构错误：{path} Stop[{index}].hooks 必须是数组")
        for hook_index, hook in enumerate(entries):
            if not isinstance(hook, dict):
                raise SystemExit(
                    f"[agent_sync] hooks 结构错误：{path} Stop[{index}].hooks[{hook_index}] 必须是对象")
            if "command" in hook and not isinstance(hook["command"], str):
                raise SystemExit(f"[agent_sync] hooks 结构错误：{path} command 必须是字符串")
            if "type" in hook and not isinstance(hook["type"], str):
                raise SystemExit(f"[agent_sync] hooks 结构错误：{path} type 必须是字符串")


def _validate_codex_features(root: Path):
    path = root / ".codex/config.toml"
    text = _read(path)
    feature_headers = list(re.finditer(r"(?m)^[ \t]*\[features\][ \t]*$", text))
    assignments = list(re.finditer(r"(?m)^[ \t]*codex_hooks[ \t]*=.*$", text))
    hook_keys = list(CODEX_HOOK_LINE_RE.finditer(text))
    if len(feature_headers) > 1:
        raise SystemExit(f"[agent_sync] Codex features 结构错误：{path} 含重复 [features] section")
    if len(assignments) > 1:
        raise SystemExit(f"[agent_sync] Codex features 结构错误：{path} 含重复 codex_hooks 键")
    if assignments and not hook_keys:
        raise SystemExit(f"[agent_sync] Codex features 结构错误：codex_hooks 必须是 true/false")
    if hook_keys:
        if not feature_headers:
            raise SystemExit(f"[agent_sync] Codex features 结构错误：codex_hooks 不在 [features] section")
        start = feature_headers[0].end()
        next_header = re.search(r"(?m)^[ \t]*\[", text[start:])
        end = start + next_header.start() if next_header else len(text)
        if not (start <= hook_keys[0].start() < end):
            raise SystemExit(f"[agent_sync] Codex features 结构错误：codex_hooks 不在 [features] section")


def _merge_codex_hook_flag(text: str) -> str:
    if CODEX_HOOK_LINE_RE.search(text):
        def replace(match):
            return (f"{match.group('indent')}codex_hooks{match.group('before')}="
                    f"{match.group('after')}true{match.group('comment')}")
        return CODEX_HOOK_LINE_RE.sub(replace, text, count=1)
    if re.search(r"(?m)^[ \t]*\[features\][ \t]*$", text):
        return re.sub(r"(?m)^([ \t]*\[features\][ \t]*)$", r"\1\ncodex_hooks = true", text, count=1)
    return (text.rstrip() + "\n\n" if text.strip() else "") + "[features]\ncodex_hooks = true\n"


def _validate_hooks(root: Path, agents: list):
    if not (root / STOP_GUARD_REL).is_file():
        return
    paths = {"claude": root / ".claude/settings.json",
             "codex": root / ".codex/hooks.json",
             "dsh": root / ".dsh/hooks.json"}
    for agent in agents:
        path = paths[agent]
        data = _json_object(path, f"{agent} hooks {path}") if path.exists() else {}
        _validate_hook_structure(data, path)
        _merge_stop_hook(json.loads(json.dumps(data)), _hook_cmd(agent))
    if "codex" in agents:
        _validate_codex_features(root)


def _validate_claude_plugins(root: Path, plugins: list):
    marker_path = root / CLAUDE_PLUGIN_MANAGED
    settings_path = root / ".claude/settings.json"
    if not plugins and not marker_path.is_file():
        return
    settings = _json_object(settings_path, "Claude settings")
    marker = _json_object(marker_path, "Claude plugin marker") if marker_path.is_file() else {}
    for field in ("marketplaces", "enabledPlugins"):
        values = marker.get(field, [])
        if not isinstance(values, list) or any(not isinstance(item, str) for item in values):
            raise SystemExit(f"[agent_sync] Claude plugin marker 字段类型错误：{field}")
    markets = settings.get("extraKnownMarketplaces", {})
    enabled = settings.get("enabledPlugins", {})
    if not isinstance(markets, dict):
        raise SystemExit("[agent_sync] Claude settings 字段类型错误：extraKnownMarketplaces 必须是对象")
    if not isinstance(enabled, dict):
        raise SystemExit("[agent_sync] Claude settings 字段类型错误：enabledPlugins 必须是对象")
    markets = dict(markets)
    enabled = dict(enabled)
    for key in marker.get("marketplaces", []):
        markets.pop(key, None)
    for key in marker.get("enabledPlugins", []):
        enabled.pop(key, None)

    for plugin in plugins:
        marketplace_path = plugin / ".claude-plugin/marketplace.json"
        marketplace = _json_object(marketplace_path, f"Claude marketplace {marketplace_path}") \
            if marketplace_path.is_file() else {}
        name = marketplace.get("name") or f"{plugin.name}-marketplace"
        entries = marketplace.get("plugins", [{"name": plugin.name}])
        if not isinstance(name, str) or not isinstance(entries, list) \
                or any(not isinstance(entry, dict) for entry in entries):
            raise SystemExit(f"[agent_sync] Claude marketplace 字段类型错误：{marketplace_path}")
        desired = {"source": {"source": "directory", "path": f"./{CLAUDE_PLUGINS}/{plugin.name}"}}
        if name in markets and markets[name] != desired:
            raise SystemExit(f"[agent_sync] Claude marketplace 用户配置冲突：{name}")
        for entry in entries:
            plugin_name = entry.get("name", plugin.name)
            if not isinstance(plugin_name, str):
                raise SystemExit(f"[agent_sync] Claude marketplace 字段类型错误：{marketplace_path}")
            key = f"{plugin_name}@{name}"
            if key in enabled and enabled[key] is not True:
                raise SystemExit(f"[agent_sync] Claude enabledPlugins 用户配置冲突：{key}")


def _validate_real_namespace(root: Path, rel: str, label: str):
    current = root
    for part in Path(rel).parts:
        current = current / part
        if current.is_symlink():
            raise SystemExit(f"[agent_sync] {label} 必须位于真实目录，拒绝 symlink：{current}")
        if current.exists() and not current.is_dir():
            raise SystemExit(f"[agent_sync] {label} 必须位于真实目录，发现非目录：{current}")


def _validate_adapter_namespaces(root: Path, plugins: list):
    namespaces = {
        ".claude", CLAUDE_SKILLS, CLAUDE_COMMANDS, CLAUDE_PLUGINS,
        ".codex", CODEX_PLUGIN_SKILLS, CODEX_COMMAND_SKILLS,
        ".dsh", DSH_COMMANDS, ".dsh/skills",
        ".agents", SHARED_SKILLS, LEGACY_CODEX_PLUGINS,
    }
    namespaces.update(f"{CODEX_PLUGIN_SKILLS}/{plugin.name}" for plugin in plugins
                      if (plugin / "skills").is_dir())
    for rel in sorted(namespaces, key=lambda item: (len(Path(item).parts), item)):
        _validate_real_namespace(root, rel, f"Agent 适配 namespace {rel}")


def _validate_targets(root: Path, agents: list, plugins: list, plugin_skills: dict):
    if "claude" in agents:
        for name in _base_skill_dirs(root):
            _require_generated_or_absent(root / CLAUDE_SKILLS / name, "Claude SKILL 入口")
        destination = root / CLAUDE_COMMANDS
        previous = _generated_names(destination / GENERATED_FILE)
        for command in _command_files(root):
            target = destination / command.name
            if ((target.exists() or target.is_symlink()) and command.name not in previous
                    and not _is_generated(target)):
                raise SystemExit(f"[agent_sync] Claude 命令目标已存在用户内容，拒绝覆盖：{target}")
        for plugin in plugins:
            _require_generated_or_absent(root / CLAUDE_PLUGINS / plugin.name,
                                         "Claude 插件目录")
    if "codex" in agents:
        for command in _command_files(root):
            _require_generated_or_absent(root / CODEX_COMMAND_SKILLS / command.stem,
                                         "Codex 命令 SKILL")
        for plugin in plugins:
            if (plugin / "skills").is_dir():
                _require_generated_or_absent(root / CODEX_PLUGIN_SKILLS / plugin.name,
                                             "Codex 插件 SKILL 目录")
    if "dsh" in agents:
        destination = root / DSH_COMMANDS
        previous = _generated_names(destination / GENERATED_FILE)
        for command in _command_files(root):
            target = destination / command.name
            if ((target.exists() or target.is_symlink()) and command.name not in previous
                    and not _is_generated(target)):
                raise SystemExit(f"[agent_sync] 原生命令目标已存在用户内容，拒绝覆盖：{target}")
    if "codex" in agents or "dsh" in agents:
        desired = _base_skill_dirs(root)
        if "dsh" in agents:
            desired = {**desired, **plugin_skills}
        for name in desired:
            _require_generated_or_absent(root / SHARED_SKILLS / name, "SKILL 入口")


def run(root: Path, agents: list, mode: str, apply: bool) -> dict:
    plugins = _plugin_dirs(root)
    plugin_skills = _plugin_skill_dirs(plugins) if ({"codex", "dsh"} & set(agents)) else {}
    public_skills = set(_base_skill_dirs(root))
    skill_clash = sorted(public_skills & set(plugin_skills))
    if skill_clash:
        raise SystemExit(f"[agent_sync] 插件 SKILL 与公共 SKILL 同名冲突：{', '.join(skill_clash)}")
    clash = _name_conflicts(root, plugin_skills)
    if clash:
        raise SystemExit(f"[agent_sync] 命令与 SKILL 同名冲突：{', '.join(clash)}，请改名其一")
    all_servers = _plugin_servers(plugins)
    _validate_adapter_namespaces(root, plugins)
    _validate_targets(root, agents, plugins, plugin_skills)
    _validate_hooks(root, agents)
    _validate_claude_plugins(root, plugins if "claude" in agents else [])
    if "codex" in agents:
        _validate_codex_mcp(root, all_servers)
    if "dsh" in agents:
        _validate_dsh_mcp(root, all_servers)

    plan = Plan(root, apply, mode)
    sync_memory(plan, agents)
    for agent in agents:
        sync_hooks(plan, agent)
    legacy_plugins = cleanup_legacy_codex_plugins(plan)
    generated = []

    if "claude" in agents:
        generated += sync_skill_dir(plan, CLAUDE_SKILLS)
        generated += sync_file_commands(plan, CLAUDE_COMMANDS)
        generated += sync_claude_plugins(plan, plugins)
    else:
        _prune(plan, root / CLAUDE_SKILLS, set())
        sync_file_commands(plan, CLAUDE_COMMANDS, enabled=False)
        sync_claude_plugins(plan, [])

    if "codex" in agents or "dsh" in agents:
        extras = plugin_skills if "dsh" in agents else {}
        generated += sync_skill_dir(plan, SHARED_SKILLS, extras)
    else:
        _prune(plan, root / SHARED_SKILLS, set())

    if "codex" in agents:
        generated += sync_codex_commands(plan)
        generated += sync_codex_plugin_skills(plan, plugins)
        sync_codex_mcp(plan, all_servers, legacy_plugins)
    else:
        _prune(plan, root / CODEX_COMMAND_SKILLS, set())
        sync_codex_plugin_skills(plan, [])
        sync_codex_mcp(plan, {}, legacy_plugins)

    if "dsh" in agents:
        generated += sync_file_commands(plan, DSH_COMMANDS)
        generated += sync_dsh_mcp(plan, all_servers)
    else:
        sync_file_commands(plan, DSH_COMMANDS, enabled=False)
        generated += sync_dsh_mcp(plan, {})

    _prune(plan, root / LEGACY_CODEX_COMMAND_SKILLS, set())
    _prune(plan, root / ".dsh/skills", set())
    sync_gitignore(plan, generated)
    return {"agents": agents, "mode": mode, "applied": apply,
            "drift": bool(plan.actions), "actions": plan.actions}


def _self_check() -> int:
    """阳性对照：三 Agent 原生命令、公共 SKILL、插件和 MCP 装配均可重复。"""
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / ".aidp/skills/demo").mkdir(parents=True)
        (root / ".aidp/skills/demo/SKILL.md").write_text(
            "---\nname: demo\ndescription: d\n---\n", encoding="utf-8")
        (root / ".aidp/commands").mkdir(parents=True)
        (root / ".aidp/commands/sprint-dev.md").write_text(
            "# /sprint-dev — 开发\n\n参数：$ARGUMENTS\n", encoding="utf-8")
        (root / ".aidp/hooks").mkdir(parents=True)
        (root / STOP_GUARD_REL).write_text("", encoding="utf-8")
        (root / "CLAUDE.md").write_text("# 正文\n", encoding="utf-8")
        (root / ".gitignore").write_text("node_modules/\n", encoding="utf-8")
        plugin = root / ".aidp/plugins/demo-plugin"
        (plugin / ".claude-plugin").mkdir(parents=True)
        (plugin / ".claude-plugin/plugin.json").write_text(json.dumps({
            "name": "demo-plugin", "version": "1.0.0",
            "mcpServers": {"demo": {"command": "npx", "args": ["demo-mcp"]}},
        }), encoding="utf-8")
        (plugin / "skills/browse").mkdir(parents=True)
        (plugin / "skills/browse/SKILL.md").write_text(
            "---\nname: browse\ndescription: b\n---\n", encoding="utf-8")
        for directory in (".claude", ".codex", ".dsh"):
            (root / directory).mkdir()

        mode = "copy" if os.name == "nt" else "link"
        agents = ["claude", "codex", "dsh"]
        first = run(root, agents, mode, apply=True)
        checks = {
            "memory": _read(root / "AGENTS.md") == "# 正文\n" and _is_shell(_read(root / "CLAUDE.md")),
            "claude command": (root / ".claude/commands/sprint-dev.md").is_file(),
            "codex command": (root / ".codex/skills/aidp/sprint-dev/SKILL.md").is_file(),
            "dsh command": (root / ".dsh/commands/sprint-dev.md").is_file(),
            "shared skill": (root / ".agents/skills/demo/SKILL.md").is_file(),
            "no router": not (root / ".agents/skills/aidp-cmd").exists(),
            "claude plugin": (root / ".claude/plugins/demo-plugin/.claude-plugin/plugin.json").is_file(),
            "codex plugin skill": (root / ".codex/skills/demo-plugin/skills/browse/SKILL.md").is_file(),
            "dsh plugin skill": (root / ".agents/skills/browse/SKILL.md").is_file(),
            "codex mcp": "[mcp_servers.demo]" in _read(root / ".codex/config.toml"),
            "dsh mcp": "demo-mcp" in _read(root / ".dsh/mcp.json"),
            "hook": "codex_hooks = true" in _read(root / ".codex/config.toml"),
            "first run": first["drift"],
            "idempotent": not run(root, agents, mode, apply=False)["drift"],
        }
        (root / ".aidp/commands/sprint-dev.md").unlink()
        checks["stale command detected"] = run(root, agents, mode, apply=False)["drift"]
        bad = [name for name, passed in checks.items() if not passed]
        print(json.dumps({"self_check": "fail" if bad else "pass", "failed": bad}, ensure_ascii=False))
        return 1 if bad else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".")
    ap.add_argument("--agents", default="", help="逗号分隔：claude,codex,dsh；缺省按项目根目录检测")
    ap.add_argument("--mode", choices=("link", "copy"), default="copy" if os.name == "nt" else "link")
    ap.add_argument("--check", action="store_true", help="只检查不写，有漂移 exit 1")
    ap.add_argument("--human", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args(argv)
    if a.self_check:
        return _self_check()
    root = Path(a.root).resolve()
    if not (root / AIDP_DIR).is_dir():
        print(json.dumps({"error": f"{root} 下没有 {AIDP_DIR}/"}, ensure_ascii=False))
        return 2
    if a.agents:
        agents = [x.strip() for x in a.agents.split(",") if x.strip()]
        unknown = [x for x in agents if x not in KNOWN_AGENTS]
        if unknown:
            print(json.dumps({"error": f"未知 Agent：{unknown}，可选 {list(KNOWN_AGENTS)}"}, ensure_ascii=False))
            return 2
    else:
        agents = detect_agents(root)
    try:
        result = run(root, agents, a.mode, apply=not a.check)
    except SystemExit as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False))
        return 2
    print(json.dumps(result, ensure_ascii=False))
    if a.human:
        for act in result["actions"]:
            print(f"  {act['op']:6} {act['path']}", file=sys.stderr)
    return 1 if (a.check and result["drift"]) else 0


if __name__ == "__main__":
    sys.exit(main())
