#!/usr/bin/env python3
"""文件复杂度检查脚本(对应 code-verification-loop 维度 4「文件复杂度 + 复用封装」)

扫描代码目录,统计:
1. 单文件行数(剔除空行 + 单行注释,按语言软阈值/2 倍阈值告警)
2. 单方法/函数行数(超过 50 行 → Critical)

退出码:
  0  无违规或仅 Important
  1  存在 Critical(单文件超 2 倍阈值 / 单方法 > 50 行)

用法:
  python check_file_complexity.py <code-dir>
  python check_file_complexity.py <code-dir> --json
  python check_file_complexity.py <code-dir> --strict      # Important 也返回非零
  python check_file_complexity.py <code-dir> --method-limit 50

豁免目录(默认跳过):
  node_modules .git dist build target out .next .nuxt vendor __pycache__
  及任何包含 generated / autogenerated / .generated 的目录段
"""
import argparse
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# 单文件软阈值(超阈值告警, 2 倍阈值升 Critical), 不含空行+单行注释
FILE_LINE_LIMITS: Dict[str, int] = {
    ".java": 500,
    ".kt": 500,
    ".kts": 500,
    ".vue": 300,
    ".tsx": 300,
    ".jsx": 300,
    ".ts": 400,
    ".js": 400,
    ".mjs": 400,
    ".py": 600,
    ".go": 500,
}

DEFAULT_METHOD_LIMIT = 50

EXCLUDED_DIRS = {
    "node_modules", ".git", "dist", "build", "target", "out",
    ".next", ".nuxt", "vendor", "__pycache__", ".idea", ".vscode",
    "coverage", ".nyc_output", "tmp", ".cache",
    # ⚠️ 测试目录必须在此:脚本输出里那句「豁免:…test fixture(已按目录名启发式跳过)」
    #    一度**没有对应实现**——同一次输出既列出 __tests__/a.spec.ts 判 Critical、
    #    又声称已跳过 test fixture,自相矛盾;而本脚本是 exit 1 硬门,测试代码会把整轮验收判失败。
    #    口径同步对齐 scan_mock_data.py(它本就排除 __tests__/tests/test)。
    "__tests__", "__test__", "tests", "test", "spec", "__specs__",
}

GENERATED_HINT = re.compile(r"(generated|autogenerated|\.generated)", re.IGNORECASE)
# ⚠️ 仅按目录名豁免不够:`Foo.spec.ts` / `Foo.test.tsx` 与源码**同目录**是
#    Vue/React/Jest 的主流约定,只覆盖 Java-Maven 式 `src/test/` 布局的话,
#    最常见的场景下「测试代码把整轮验收判失败」依然成立(本脚本是 exit 1 硬门)。
TEST_FILE_HINT = re.compile(
    r"\.(spec|test)\.[jt]sx?$|(^|[/\\])test_[^/\\]+\.py$|_test\.(go|py)$|Test(s)?\.(java|kt|cs)$|Spec\.(java|kt|groovy)$", re.IGNORECASE)

# 各语言的方法/函数声明粗略 regex(仅用于定位起点)
METHOD_PATTERNS: Dict[str, List[re.Pattern]] = {
    "java": [
        re.compile(r"^\s*(?:public|protected|private|static|final|abstract|synchronized|\s)+[\w<>\[\]]+\s+(\w+)\s*\([^)]*\)\s*(?:throws[^{]+)?\{"),
    ],
    "kotlin": [re.compile(r"^\s*(?:override\s+|open\s+|private\s+|public\s+|protected\s+|internal\s+|suspend\s+)*fun\s+(\w+)\s*\(")],
    "ts": [
        re.compile(r"^\s*(?:export\s+)?(?:async\s+)?function\s+(\w+)\s*\("),
        re.compile(r"^\s*(?:public|private|protected|static|async|\s)+(\w+)\s*\([^)]*\)\s*[:{]"),
        re.compile(r"^\s*(\w+)\s*[=:]\s*(?:async\s*)?\([^)]*\)\s*=>"),
    ],
    "py": [re.compile(r"^\s*(?:async\s+)?def\s+(\w+)\s*\(")],
    "go": [re.compile(r"^func\s+(?:\([^)]*\)\s+)?(\w+)\s*\(")],
}

# 各语言的单行注释起点(用于"代码有效行数"统计)
SINGLE_LINE_COMMENT: Dict[str, Tuple[str, ...]] = {
    ".java": ("//",),
    ".kt": ("//",),
    ".kts": ("//",),
    ".ts": ("//",),
    ".tsx": ("//",),
    ".js": ("//",),
    ".jsx": ("//",),
    ".mjs": ("//",),
    ".vue": ("//",),
    ".go": ("//",),
    ".py": ("#",),
}


def lang_key(ext: str) -> Optional[str]:
    if ext in (".java",):
        return "java"
    if ext in (".kt", ".kts"):
        return "kotlin"
    if ext in (".ts", ".tsx", ".js", ".jsx", ".mjs", ".vue"):
        return "ts"
    if ext == ".py":
        return "py"
    if ext == ".go":
        return "go"
    return None


def is_excluded(path: Path, root: Path) -> bool:
    """仅基于 root 以内的相对路径判断排除,避免项目位于
    /tmp、/home/xx/build 等含排除名祖先目录时被整体跳过"""
    try:
        rel = path.relative_to(root)
    except ValueError:
        rel = path
    parts = set(rel.parts)
    if TEST_FILE_HINT.search(str(path).replace("\\", "/")):
        return True
    if parts & EXCLUDED_DIRS:
        return True
    if GENERATED_HINT.search(str(rel)):
        return True
    return False


def count_effective_lines(text: str, ext: str) -> int:
    """剔除空行 + 单行注释后的代码行数"""
    comments = SINGLE_LINE_COMMENT.get(ext, ())
    n = 0
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if comments and any(stripped.startswith(c) for c in comments):
            continue
        n += 1
    return n


def find_long_methods(text: str, ext: str, limit: int) -> List[Dict]:
    """粗略大括号/缩进匹配定位方法体长度. 不依赖外部解析器,可能有 false positive,
    但对常见单方法 > 50 行的明显违规足以告警."""
    key = lang_key(ext)
    if key is None or key not in METHOD_PATTERNS:
        return []
    lines = text.splitlines()
    violations: List[Dict] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        match = None
        for pat in METHOD_PATTERNS[key]:
            m = pat.search(line)
            if m:
                match = m
                break
        if not match:
            i += 1
            continue
        name = match.group(1) if match.groups() else "<anonymous>"
        start = i + 1
        end = _scan_method_end(lines, i, key)
        if end is None:
            i += 1
            continue
        # 有效行数(剔除空行 + 单行注释)
        body = "\n".join(lines[i:end + 1])
        eff = count_effective_lines(body, ext)
        if eff > limit:
            violations.append({
                "name": name,
                "start_line": start,
                "end_line": end + 1,
                "effective_lines": eff,
            })
        i = end + 1
    return violations


def _scan_method_end(lines: List[str], start: int, key: str) -> Optional[int]:
    """从方法声明行开始, 按语言寻找方法体结束行"""
    if key == "py":
        # Python 用缩进
        if start >= len(lines):
            return None
        # 找到下一行非空内容的缩进
        base_indent = len(lines[start]) - len(lines[start].lstrip())
        for j in range(start + 1, len(lines)):
            stripped = lines[j].strip()
            if not stripped:
                continue
            indent = len(lines[j]) - len(lines[j].lstrip())
            if indent <= base_indent:
                return j - 1
        return len(lines) - 1
    # 大括号语言
    depth = 0
    started = False
    for j in range(start, len(lines)):
        # 简化处理: 忽略字符串/注释内的大括号(粗略,可能有 false positive)
        for ch in lines[j]:
            if ch == "{":
                depth += 1
                started = True
            elif ch == "}":
                depth -= 1
                if started and depth == 0:
                    return j
    return None


def scan(root: Path, method_limit: int) -> Dict:
    file_warnings: List[Dict] = []
    file_criticals: List[Dict] = []
    method_violations: List[Dict] = []
    scanned_files = 0
    unreadable_files: List[str] = []

    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if is_excluded(path, root):
            continue
        ext = path.suffix.lower()
        limit = FILE_LINE_LIMITS.get(ext)
        if limit is None:
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except (OSError, UnicodeDecodeError):
            # ⚠️ 读不出来 ≠ 该文件无违规。静默 continue 会让 `chmod 000` 的文件
            # 连同其中的违规一起蒸发，输出「✅ 通过」exit 0。如实登记，交调用方判断。
            try:
                unreadable_files.append(str(path.relative_to(root)))
            except ValueError:
                unreadable_files.append(str(path))
            continue
        scanned_files += 1
        eff = count_effective_lines(text, ext)
        try:
            rel = str(path.relative_to(root))
        except ValueError:
            rel = str(path)
        if eff > limit * 2:
            file_criticals.append({
                "file": rel,
                "effective_lines": eff,
                "limit": limit,
                "ratio": round(eff / limit, 2),
            })
        elif eff > limit:
            file_warnings.append({
                "file": rel,
                "effective_lines": eff,
                "limit": limit,
                "ratio": round(eff / limit, 2),
            })
        # 单方法/函数检查
        long_methods = find_long_methods(text, ext, method_limit)
        for m in long_methods:
            method_violations.append({"file": rel, **m})

    return {
        # ⚠️ `scanned_files` / `skipped` 必须有（CLAUDE.md「三条不可回退的约定」第 3 条）：
        # 没有它时，「纯 .md 目录 / 空目录 / 路径写成上层 / 整目录被 EXCLUDED_DIRS 吃掉」
        # 四种「整档没跑」与「真通过」的 JSON 输出逐字相同，调用方无从区分。
        "scanned_files": scanned_files,
        "skipped": scanned_files == 0,
        "unreadable_files": unreadable_files,
        "file_criticals": file_criticals,
        "file_warnings": file_warnings,
        "method_violations": method_violations,
        "method_limit": method_limit,
    }


def render_text(result: Dict) -> str:
    out: List[str] = []
    out.append("=== 文件复杂度 + 复用封装 检查 ===")
    crits = result["file_criticals"]
    warns = result["file_warnings"]
    methods = result["method_violations"]
    out.append(f"\n🔴 Critical 单文件超 2 倍阈值: {len(crits)}")
    for c in crits:
        out.append(f"  - {c['file']}  {c['effective_lines']} 行 (阈值 {c['limit']}, 倍数 {c['ratio']}x)")
    out.append(f"\n🟡 Important 单文件超阈值: {len(warns)}")
    for w in warns:
        out.append(f"  - {w['file']}  {w['effective_lines']} 行 (阈值 {w['limit']}, 倍数 {w['ratio']}x)")
    out.append(f"\n🔴 Critical 单方法/函数 > {result['method_limit']} 行: {len(methods)}")
    for m in methods:
        out.append(f"  - {m['file']}:{m['start_line']}  {m['name']}()  {m['effective_lines']} 行")
    if not crits and not warns and not methods:
        out.append("\n✅ 全部通过")
    out.append("\n豁免: 自动生成代码、第三方代码搬运、一次性迁移脚本、test fixture(已按目录名启发式跳过)")
    return "\n".join(out)


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("root", type=Path, help="代码根目录")
    parser.add_argument("--json", action="store_true", help="JSON 格式输出供 Agent 解析")
    parser.add_argument("--strict", action="store_true", help="Important 也返回非零退出码")
    parser.add_argument("--method-limit", type=int, default=DEFAULT_METHOD_LIMIT, help=f"单方法/函数行数硬阈值(默认 {DEFAULT_METHOD_LIMIT})")
    args = parser.parse_args(argv)

    # ⚠️ `exists()` 与 `is_dir()` 必须分开判（CLAUDE.md「三条不可回退的约定」第 2 条）。
    # 合并写成 `if not X.exists(): return 2` 时，传**存在的单个文件**会一路跑到
    # `rglob("*")` 拿到空集 → 0 命中 → exit 0「✅ 通过」。手滑把目录写成文件路径，
    # 等于整个检查静默放行。实测同一份含 63 行超长方法的代码：传目录 exit 1、
    # 传该文件本身 exit 0，输出的 JSON 全空。
    if not args.root.exists():
        print(f"错误: 路径不存在 {args.root}", file=sys.stderr)
        return 2
    if not args.root.is_dir():
        print(f"错误: 需要目录，收到的是文件 {args.root}", file=sys.stderr)
        return 2

    result = scan(args.root, args.method_limit)

    if args.json:
        print(json.dumps(result, ensure_ascii=False, indent=2))
    else:
        print(render_text(result))

    has_critical = bool(result["file_criticals"]) or bool(result["method_violations"])
    has_warning = bool(result["file_warnings"])
    if has_critical:
        return 1
    if args.strict and has_warning:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
