#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""把 `AIDP_HOME/` 单一信源装配成 Claude Code、Codex 与 DeepSeek Harness 的项目入口。

目录契约：

| Agent | 公共 SKILL | 命令入口 | chrome-devtools-mcp |
|-------|------------|----------|---------------------|
| Claude Code | `.claude/skills/` | `.claude/commands/*.md` | `.claude/plugins/<name>/` |
| Codex | `.agents/skills/` | `.codex/skills/aidp/<command>/SKILL.md` | `.agents/skills/<name>/skills/` + `.codex/config.toml` MCP |
| DeepSeek Harness | `.agents/skills/` | `.dsh/commands/*.md` | `.agents/skills/<name>/skills/` + `.dsh/mcp.json` |

`AIDP_HOME/commands/`、`AIDP_HOME/skills/`、`AIDP_HOME/plugins/` 始终是唯一真源。生成入口统一使用带标记的
managed-copy；兼容参数 `--mode link` 只报告归一化，不再创建符号链接。只清理由本脚本生成的内容，
保留用户自有配置和入口。Codex 命令逐条生成显式调用 SKILL，DSH 由项目扩展读取原生命令文件。

用法：

    python3 AIDP_HOME/scripts/agent_sync.py
    python3 AIDP_HOME/scripts/agent_sync.py --agents claude,codex,dsh
    python3 AIDP_HOME/scripts/agent_sync.py --mode copy
    python3 AIDP_HOME/scripts/agent_sync.py --check
    python3 AIDP_HOME/scripts/agent_sync.py --self-check

stdout 恒为一行 JSON（`--human` 另输出人读摘要到 stderr）。
退出码：0 = 已一致 / 已写入；1 = `--check` 发现漂移；2 = 参数或环境错误。
"""
import sys as _aidp_sys
from pathlib import Path as _AidpPath
_aidp_scripts = str(_AidpPath(__file__).resolve().parent)
if _aidp_scripts not in _aidp_sys.path:
    _aidp_sys.path.insert(0, _aidp_scripts)
from aidp_runtime import runtime_root, runtime_text
import argparse
import hashlib
import json
import os
import re
import shlex
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from agent_env import detect_agents, KNOWN_AGENTS  # noqa: E402

LEGACY_AIDP_DIR = ".aidp"
RUNTIME_ROOT = runtime_root(__file__)
SHELL_BODY = "@AGENTS.md\n"
STOP_GUARD_SOURCE = RUNTIME_ROOT / "hooks/autopilot-stop-guard.py"
STOP_GUARD_REL = runtime_text('__AIDP_HOME__/hooks/autopilot-stop-guard.py', __file__)
AGENT_RUNTIME_HOME = {"claude": ".claude" + "/aidp", "codex": ".agents" + "/aidp",
                      "dsh": ".agents" + "/aidp"}
GENERATED_MARK = runtime_text('<!-- generated by __AIDP_HOME__/scripts/agent_sync.py; edit __AIDP_HOME__/commands instead -->', __file__)
GENERATED_FILE = ".aidp-generated"
OBSOLETE_ROUTER = "aidp-cmd"

CLAUDE_SKILLS = ".claude/skills"
SHARED_SKILLS = ".agents/skills"
CLAUDE_COMMANDS = ".claude/commands"
CODEX_COMMAND_SKILLS = ".codex/skills/aidp"
LEGACY_CODEX_COMMAND_SKILLS = ".codex/aidp/skills"
DSH_COMMANDS = ".dsh/commands"
PLUGINS_SRC = "plugins"
CLAUDE_PLUGINS = ".claude/plugins"
CODEX_PLUGIN_SKILLS = ".codex/skills"
OPENAI_YAML = "policy:\n  allow_implicit_invocation: false\n"
CODEX_BODY_MARKER = "## 原始命令正文（逐字保真）\n\n"
CODEX_MCP_BEGIN = "# >>> AIDP-MCP {name} >>>"
CODEX_MCP_END = "# <<< AIDP-MCP {name} <<<"
DSH_MCP_MANAGED = ".dsh/.aidp-mcp-servers.json"
CLAUDE_PLUGIN_MANAGED = ".claude/.aidp-plugins.json"
LEGACY_CODEX_PLUGINS = ".agents/plugins"
CODEX_MCP_SUPPORTED_FIELDS = {
    "command", "args", "url", "enabled", "startup_timeout_sec", "tool_timeout_sec",
}
GITIGNORE_BEGIN = runtime_text('# >>> AIDP-AGENT-ADAPTERS（由 __AIDP_HOME__/scripts/agent_sync.py 生成，勿手改）>>>', __file__)
GITIGNORE_END = "# <<< AIDP-AGENT-ADAPTERS <<<"
CODEX_HOOK_LINE_RE = re.compile(
    r"(?m)^(?P<indent>[ \t]*)codex_hooks(?P<before>[ \t]*)="
    r"(?P<after>[ \t]*)(?P<value>true|false)(?P<comment>[ \t]*(?:#.*)?)$"
)


# ── 通用小工具 ────────────────────────────────────────────────────────────────
def _read(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""


def _frontmatter(text: str) -> dict:
    """只解析 `key: value` 单行形式，够读 description / argument-hint。"""
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n", text, re.S)
    out = {}
    if not m:
        return out
    for line in m.group(1).splitlines():
        kv = re.match(r"^([A-Za-z_-]+)\s*:\s*(.*)$", line)
        if kv:
            out[kv.group(1)] = kv.group(2).strip().strip('"').strip("'")
    return out


def _title_description(text: str) -> str:
    """命令文件无 frontmatter 时，取首个 H1「# /name — 说明」里破折号后的说明（去掉标题装饰符 ★）。"""
    m = re.search(r"^#\s+/?[\w-]+\s*[—-]+\s*(.+?)\s*$", text, re.M)
    if not m:
        return ""
    desc = re.sub(r"[（(]\s*★\s*[)）]|★", "", m.group(1)).strip()
    return f"AIDP 命令：{desc}"


def _is_shell(text: str) -> bool:
    body = [l for l in text.splitlines() if l.strip() and not l.strip().startswith("<!--")]
    return len(body) == 1 and body[0].strip() == "@AGENTS.md"


def _lexical(path: Path) -> Path:
    return Path(os.path.abspath(os.path.normpath(os.fspath(path))))


def _source_boundary(root: Path, source: Path) -> Path:
    root_abs = _lexical(root)
    source_abs = _lexical(source)
    candidates = (RUNTIME_ROOT, root / ("." + "aidp"),
                  root / AGENT_RUNTIME_HOME["claude"], root / AGENT_RUNTIME_HOME["codex"])
    for candidate in candidates:
        boundary = _lexical(candidate)
        try:
            boundary.relative_to(root_abs)
            source_abs.relative_to(boundary)
            return boundary
        except ValueError:
            continue
    raise SystemExit(f"[agent_sync] 复制源路径越出 AIDP 运行包：{source}")


def _validate_real_chain(root: Path, target: Path):
    root_abs = _lexical(root)
    target_abs = _lexical(target)
    try:
        parts = target_abs.relative_to(root_abs).parts
    except ValueError as exc:
        raise SystemExit(f"[agent_sync] 复制源路径越出项目根：{target}") from exc
    current = root_abs
    try:
        root_info = current.lstat()
    except OSError as exc:
        raise SystemExit(f"[agent_sync] 项目根不存在：{current}：{exc}")
    if stat.S_ISLNK(root_info.st_mode) or not stat.S_ISDIR(root_info.st_mode):
        raise SystemExit(f"[agent_sync] 项目根必须是实体目录：{current}")
    for part in parts:
        current = current / part
        try:
            info = current.lstat()
        except OSError as exc:
            raise SystemExit(f"[agent_sync] 复制源不存在：{current}：{exc}")
        if stat.S_ISLNK(info.st_mode):
            raise SystemExit(f"[agent_sync] 复制源祖先包含 symlink：{current}")
        if not stat.S_ISDIR(info.st_mode):
            raise SystemExit(f"[agent_sync] 复制源祖先不是目录：{current}")


def _validate_material_path(root: Path, source: Path, expect_dir: bool):
    """从可信项目根开始，不跟随链接地验证复制源。"""
    boundary = _source_boundary(root, source)
    source_abs = _lexical(source)
    _validate_real_chain(root, boundary)
    if source_abs != boundary:
        _validate_real_chain(root, source_abs.parent)

    info = source_abs.lstat()
    if expect_dir and not stat.S_ISDIR(info.st_mode):
        raise SystemExit(f"[agent_sync] 复制源必须是目录：{source_abs}")
    if not expect_dir:
        if not stat.S_ISREG(info.st_mode):
            raise SystemExit(f"[agent_sync] 复制源必须是普通文件：{source_abs}")
        if info.st_nlink != 1:
            raise SystemExit(f"[agent_sync] 复制源文件存在硬链接：{source_abs}")
        return

    for dirpath, dirnames, filenames in os.walk(source_abs, followlinks=False):
        base = Path(dirpath)
        for name in list(dirnames) + list(filenames):
            path = base / name
            child = path.lstat()
            if stat.S_ISLNK(child.st_mode):
                raise SystemExit(f"[agent_sync] 复制源包含 symlink：{path}")
            if name in dirnames:
                if not stat.S_ISDIR(child.st_mode):
                    raise SystemExit(f"[agent_sync] 复制源包含非目录节点：{path}")
            else:
                if not stat.S_ISREG(child.st_mode):
                    raise SystemExit(f"[agent_sync] 复制源包含非普通文件：{path}")
                if child.st_nlink != 1:
                    raise SystemExit(f"[agent_sync] 复制源文件存在硬链接：{path}")


def _file_record(path: Path) -> dict:
    info = path.lstat()
    if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
        raise SystemExit(f"[agent_sync] 受管文件不是单链接普通文件，冲突：{path}")
    return {"sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "mode": format(info.st_mode & 0o777, "04o")}


def _directory_inventory(root: Path) -> dict:
    if root.is_symlink() or not root.is_dir():
        raise SystemExit(f"[agent_sync] 受管目录不是实体目录，冲突：{root}")
    entries = {".": {"type": "dir", "mode": format(root.lstat().st_mode & 0o777, "04o")}}
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        base = Path(dirpath)
        for name in sorted(dirnames + filenames):
            path = base / name
            if path == root / GENERATED_FILE:
                continue
            info = path.lstat()
            rel = path.relative_to(root).as_posix()
            if stat.S_ISDIR(info.st_mode):
                entries[rel] = {"type": "dir", "mode": format(info.st_mode & 0o777, "04o")}
            elif stat.S_ISREG(info.st_mode) and info.st_nlink == 1:
                entries[rel] = {"type": "file", **_file_record(path)}
            else:
                raise SystemExit(f"[agent_sync] 受管目录包含非实体或硬链接节点，冲突：{path}")
    return entries


def _directory_marker(root: Path) -> str:
    return json.dumps({"schema": "aidp.adapter/v1", "entries": _directory_inventory(root)},
                      ensure_ascii=False, sort_keys=True) + "\n"


def _check_managed_directory(path: Path, source: Path = None):
    if path.is_symlink():
        return
    marker = path / GENERATED_FILE
    try:
        data = json.loads(_read(marker))
    except (ValueError, TypeError):
        data = None
    current = _directory_inventory(path)
    if (path.parent.name == "plugins" and path.parent.parent.name == ".agents"
            and _read(marker) == "" and set(current) == {".", "plugin.json"}):
        try:
            legacy = json.loads(_read(path / "plugin.json"))
        except json.JSONDecodeError:
            legacy = None
        if legacy == {"name": path.name}:
            return
    if isinstance(data, dict) and data.get("schema") == "aidp.adapter/v1":
        if data.get("entries") != current:
            raise SystemExit(f"[agent_sync] 受管目录已被修改或追加，冲突：{path}")
        return
    if _read(marker) != "directory-copy\n" or source is None or not _tree_equal(source, path):
        raise SystemExit(f"[agent_sync] 旧受管目录无有效清单且内容不一致，冲突：{path}")


def _validate_staged_tree(stage: Path):
    info = stage.lstat()
    if not stat.S_ISDIR(info.st_mode) or stat.S_ISLNK(info.st_mode):
        raise SystemExit(f"[agent_sync] 临时目录不是实体目录：{stage}")
    for dirpath, dirnames, filenames in os.walk(stage, followlinks=False):
        base = Path(dirpath)
        for name in list(dirnames) + list(filenames):
            path = base / name
            child = path.lstat()
            if stat.S_ISLNK(child.st_mode):
                raise SystemExit(f"[agent_sync] 临时副本包含 symlink：{path}")
            if name in dirnames:
                if not stat.S_ISDIR(child.st_mode):
                    raise SystemExit(f"[agent_sync] 临时副本包含非目录节点：{path}")
            elif not stat.S_ISREG(child.st_mode) or child.st_nlink != 1:
                raise SystemExit(f"[agent_sync] 临时副本包含非普通或硬链接文件：{path}")


class Plan:
    """收集动作；apply=False 时只记录不落盘。"""

    def __init__(self, root: Path, apply: bool, mode: str):
        self.root, self.apply = root, apply
        self.requested_mode = mode
        self.mode = "copy"
        self.actions = []
        if mode == "link":
            self.actions.append({"op": "normalized", "action": "normalized", "path": "",
                                 "from": "link", "to": "managed-copy"})

    @property
    def drift(self) -> bool:
        return any(action.get("op") not in (None, "normalized") for action in self.actions)

    def _rel(self, p: Path) -> str:
        return p.relative_to(self.root).as_posix()

    def write_text(self, p: Path, text: str):
        if _read(p) == text and p.is_file() and not p.is_symlink() and p.stat().st_nlink == 1:
            return
        self.actions.append({"op": "write", "path": self._rel(p)})
        if self.apply:
            p.parent.mkdir(parents=True, exist_ok=True)
            fd, raw = tempfile.mkstemp(prefix=f".{p.name}.stage-", dir=str(p.parent))
            os.close(fd)
            stage = Path(raw)
            try:
                # ⛔ 不用 write_text：Windows 文本模式会把 \n 写成 \r\n，与真源 LF 字节比较必然假漂移。
                stage.write_bytes(text.encode("utf-8"))
                os.chmod(stage, 0o644)
                info = stage.lstat()
                if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
                    raise SystemExit(f"[agent_sync] 临时文件不是单链接普通文件：{stage}")
                self._atomic_replace(p, stage)
            finally:
                if os.path.lexists(stage):
                    self._remove(stage)

    def link_dir(self, dst: Path, src: Path):
        """兼容旧调用名；新布局始终生成带标记的实体目录副本。"""
        _validate_material_path(self.root, src, expect_dir=True)
        if os.path.lexists(dst) and not dst.is_symlink():
            _check_managed_directory(dst, src)
        if dst.is_dir() and not dst.is_symlink() and _tree_equal(src, dst):
            if _read(dst / GENERATED_FILE) == _directory_marker(dst):
                return
            self.write_text(dst / GENERATED_FILE, _directory_marker(dst))
            return
        self.actions.append({"op": "copy", "path": self._rel(dst), "from": self._source_label(src)})
        if self.apply:
            dst.parent.mkdir(parents=True, exist_ok=True)
            stage = Path(tempfile.mkdtemp(prefix=f".{dst.name}.stage-", dir=str(dst.parent)))
            try:
                shutil.copytree(src, stage, symlinks=True, dirs_exist_ok=True,
                                ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
                (stage / GENERATED_FILE).write_bytes(_directory_marker(stage).encode("utf-8"))
                _validate_material_path(self.root, src, expect_dir=True)
                _validate_staged_tree(stage)
                if not _tree_equal(src, stage):
                    raise SystemExit("[agent_sync] 复制期间源目录发生变化，拒绝替换")
                self._atomic_replace(dst, stage)
            finally:
                if os.path.lexists(stage):
                    self._remove(stage)

    def link_file(self, dst: Path, src: Path):
        """兼容旧调用名；新布局始终生成保留 mode 的实体文件副本。"""
        _validate_material_path(self.root, src, expect_dir=False)
        if (dst.is_file() and not dst.is_symlink() and dst.stat().st_nlink == 1
                and dst.read_bytes() == src.read_bytes()
                and (dst.stat().st_mode & 0o777) == (src.stat().st_mode & 0o777)):
            return
        self.actions.append({"op": "copy", "path": self._rel(dst), "from": self._source_label(src)})
        if self.apply:
            dst.parent.mkdir(parents=True, exist_ok=True)
            fd, raw = tempfile.mkstemp(prefix=f".{dst.name}.stage-", dir=str(dst.parent))
            os.close(fd)
            stage = Path(raw)
            try:
                shutil.copy2(src, stage, follow_symlinks=False)
                _validate_material_path(self.root, src, expect_dir=False)
                info = stage.lstat()
                source_info = src.lstat()
                if not stat.S_ISREG(info.st_mode) or info.st_nlink != 1:
                    raise SystemExit(f"[agent_sync] 临时文件不是单链接普通文件：{stage}")
                if (source_info.st_nlink != 1 or stage.read_bytes() != src.read_bytes()
                        or (info.st_mode & 0o777) != (source_info.st_mode & 0o777)):
                    raise SystemExit("[agent_sync] 复制期间源文件发生变化，拒绝替换")
                self._atomic_replace(dst, stage)
            finally:
                if os.path.lexists(stage):
                    self._remove(stage)

    def _atomic_replace(self, dst: Path, stage: Path):
        had_previous = os.path.lexists(dst)
        previous = None
        installed = False
        try:
            if had_previous:
                fd, raw = tempfile.mkstemp(
                    prefix=f".{dst.name}.previous-", dir=str(dst.parent))
                os.close(fd)
                previous = Path(raw)
                previous.unlink()
                os.replace(dst, previous)
            try:
                os.replace(stage, dst)
                installed = True
            except Exception:
                if had_previous and previous is not None and os.path.lexists(previous):
                    os.replace(previous, dst)
                raise
        finally:
            if not installed and not os.path.lexists(dst) and had_previous \
                    and previous is not None and os.path.lexists(previous):
                os.replace(previous, dst)
            if previous is not None and os.path.lexists(previous):
                self._remove(previous)

    def _source_label(self, src: Path) -> str:
        try:
            return src.relative_to(self.root).as_posix()
        except ValueError:
            try:
                return "AIDP_HOME/" + src.relative_to(RUNTIME_ROOT).as_posix()
            except ValueError:
                return str(src)

    def remove(self, p: Path, why: str):
        if not (p.exists() or p.is_symlink()):
            return
        if p.is_dir() and not p.is_symlink() and (p / GENERATED_FILE).is_file():
            _check_managed_directory(p)
        self.actions.append({"op": "remove", "path": self._rel(p), "why": why})
        if self.apply:
            self._remove(p)

    @staticmethod
    def _remove(p: Path):
        if p.is_symlink() or p.is_file():
            p.unlink()
        elif p.is_dir():
            shutil.rmtree(p)


def _tree_equal(a: Path, b: Path) -> bool:
    def inventory(base):
        directories = {}
        files = {}
        for path in base.rglob("*"):
            rel = path.relative_to(base)
            if "__pycache__" in rel.parts or path.suffix == ".pyc" or path.name == GENERATED_FILE:
                continue
            if path.is_symlink():
                return None
            key = rel.as_posix()
            info = path.stat()
            mode = info.st_mode & 0o777
            if path.is_dir():
                directories[key] = mode
            elif path.is_file():
                if info.st_nlink != 1:
                    return None
                files[key] = (mode, path.read_bytes())
            else:
                return None
        return directories, files

    left = inventory(a)
    right = inventory(b)
    return left is not None and right is not None and left == right


# ── 记忆文件 ──────────────────────────────────────────────────────────────────
def sync_memory(plan: Plan, agents: list):
    root = plan.root
    agents_md, claude_md = root / "AGENTS.md", root / "CLAUDE.md"
    a_txt, c_txt = _read(agents_md), _read(claude_md)
    c_body = c_txt if (c_txt and not _is_shell(c_txt)) else ""
    a_body = a_txt if (a_txt and not _is_shell(a_txt)) else ""
    only_claude = agents == ["claude"]

    if only_claude:
        if c_body:
            return  # 正文已在 CLAUDE.md
        if a_body:
            # 正文在 AGENTS.md：保持单一正文，CLAUDE.md 做导入薄壳（Claude Code 读 CLAUDE.md）
            plan.write_text(claude_md, SHELL_BODY)
        return

    # 存在非 Claude Agent：正文必须在 AGENTS.md
    if not a_body and c_body:
        plan.write_text(agents_md, c_body)  # 搬正文，⛔ 不丢
        a_body = c_body
    if "claude" in agents and a_body:
        plan.write_text(claude_md, SHELL_BODY)


# ── 原生命令与 SKILL 入口 ────────────────────────────────────────────────────
def _command_files(root: Path) -> list:
    src = RUNTIME_ROOT / "commands"
    if not src.is_dir():
        return []
    return [p for p in sorted(src.glob("*.md")) if p.stem.upper() != "README"]


def _command_description(name: str, text: str) -> str:
    frontmatter = _frontmatter(text)
    if frontmatter.get("description"):
        return frontmatter["description"].replace('"', "'")
    match = re.search(r"^#\s+(.+?)\s*$", text, re.M)
    return (match.group(1).strip() if match else f"AIDP command {name}").replace('"', "'")


def _codex_command_preamble(name: str) -> str:
    return (
        "## Codex 命令适配规则\n\n"
        f"1. 用户以 `${name} args` 调用本命令时，`args` 的全部文字原样作为本命令的 `$ARGUMENTS`；"
        "不增删、不改写、不调整顺序与引号。\n"
        "2. 当下方原始命令正文明确调用或串联 `/foo args` 时，不依赖隐式 SKILL 调用，而是读取 "
        f"`{AGENT_RUNTIME_HOME['codex']}/commands/<命令名>.md`（此处命令名为 `foo`）。确认文件存在后，将 `args` 原样作为"
        "子命令的 `$ARGUMENTS`，在当前执行链内联执行。\n"
        "3. 被引用的命令文件不存在、命令名未知或无法唯一映射时，必须 fail closed：停止执行并报告未知命令，严禁猜测或跳过。\n"
        "4. 本适配层只负责参数传递和命令串联；不得改写下方原始命令正文。\n\n"
    )


def codex_command_skill(name: str, command_text: str) -> str:
    return (
        "---\n"
        f"name: {name}\n"
        f'description: "{_command_description(name, command_text)}"\n'
        "disable-model-invocation: true\n"
        "user-invocable: true\n"
        "---\n\n"
        f"{_codex_command_preamble(name)}"
        f"{CODEX_BODY_MARKER}"
        f"{command_text}"
    )


def cleanup_legacy_link_is_generated(root: Path, path: Path) -> bool:
    """仅接受词法落在项目旧运行真源子树内的 legacy symlink。"""
    if not path.is_symlink():
        return False
    try:
        raw = Path(os.readlink(path))
    except OSError:
        return False
    target = _lexical(raw if raw.is_absolute() else path.parent / raw)
    root_abs = _lexical(root)
    try:
        relative = target.relative_to(root_abs)
    except ValueError:
        return False
    parts = relative.parts
    return (len(parts) >= 3 and parts[0] == LEGACY_AIDP_DIR
            and parts[1] in {"commands", "skills", "plugins"})


def _is_generated(p: Path, root: Path) -> bool:
    if p.is_symlink():
        return cleanup_legacy_link_is_generated(root, p)
    if p.is_dir():
        skill_text = _read(p / "SKILL.md")
        return ((p / GENERATED_FILE).is_file() or GENERATED_MARK in skill_text
                or runtime_text('命令表由 __AIDP_HOME__/scripts/agent_sync.py', __file__) in skill_text)
    return GENERATED_MARK in _read(p) or (p.name == "marketplace.json" and _read(p.parent / GENERATED_FILE) == "marketplace\n")


def _prune(plan: Plan, base: Path, wanted: set):
    """只遍历 root 内无 symlink 祖先的真实目录，绝不跨越适配边界。"""
    try:
        relative = base.relative_to(plan.root)
    except ValueError:
        return
    current = plan.root
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            return
    if not base.is_dir():
        return
    for p in sorted(base.iterdir()):
        if p.name not in wanted and _is_generated(p, plan.root):
            plan.remove(p, "not generated anymore")


def _require_generated_or_absent(root: Path, path: Path, label: str):
    if (path.exists() or path.is_symlink()) and not _is_generated(path, root):
        raise SystemExit(f"[agent_sync] {label} 已存在用户内容，拒绝覆盖：{path}")


# 脚手架 bundle 里 SKILL.md 被遮名成 SKILL.md.in（避免递归发现的 Agent 在初始化前就注册它们）。
# ⛔ 识别 SKILL 时两种名字都要认：scaffold 的适配层预检会把 RUNTIME_ROOT 临时指向 bundle，
#    只认 SKILL.md 就会**一个公共 SKILL 都发现不到**，命令/SKILL/插件的重名冲突检测当场空跑。
SKILL_ENTRY_NAMES = ("SKILL.md", "SKILL.md.in")


def _skill_entry(directory: Path):
    """目录里的 SKILL 声明文件（兼容 bundle 遮名）；没有则 None。"""
    for name in SKILL_ENTRY_NAMES:
        candidate = directory / name
        if candidate.is_file():
            return candidate
    return None


def _base_skill_dirs(root: Path) -> dict:
    source = RUNTIME_ROOT / "skills"
    if not source.is_dir():
        return {}
    return {p.name: p for p in sorted(source.iterdir())
            if p.name not in {OBSOLETE_ROUTER, "aidp-code-engineer"}
            and _skill_entry(p) is not None}


def sync_skill_dir(plan: Plan, rel: str, preserve: set = None) -> list:
    skills = _base_skill_dirs(plan.root)
    generated = []
    destination = plan.root / rel
    for name, source in sorted(skills.items()):
        target = destination / name
        _require_generated_or_absent(plan.root, target, "SKILL 入口")
        plan.link_dir(target, source)
        generated.append(f"{rel}/{name}")
    _prune(plan, destination, set(skills) | set(preserve or ()))
    return generated


def _generated_names(path: Path) -> set:
    try:
        data = json.loads(_read(path) or "[]")
    except json.JSONDecodeError:
        return set()
    if isinstance(data, dict) and data.get("schema") == "aidp.commands/v1":
        return set(data.get("files", {}))
    return {str(item) for item in data if isinstance(item, str)} if isinstance(data, list) else set()


def _command_ledger(path: Path) -> dict:
    try:
        data = json.loads(_read(path) or "[]")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] 命令账本损坏，冲突：{path}")
    if isinstance(data, dict) and data.get("schema") == "aidp.commands/v1" \
            and isinstance(data.get("files"), dict):
        return data["files"]
    if isinstance(data, list) and all(isinstance(item, str) for item in data):
        return {item: None for item in data}
    raise SystemExit(f"[agent_sync] 命令账本格式错误，冲突：{path}")


def _check_command(root: Path, path: Path, expected: dict, source: Path = None):
    if path.is_symlink():
        if source is not None and cleanup_legacy_link_is_generated(root, path):
            return
        raise SystemExit(f"[agent_sync] 命令入口 symlink 未经授权，冲突：{path}")
    if not path.is_file():
        raise SystemExit(f"[agent_sync] 受管命令缺失或类型改变，冲突：{path}")
    current = _file_record(path)
    if expected is not None:
        if current != expected:
            raise SystemExit(f"[agent_sync] 受管命令被修改，冲突：{path}")
    elif source is None or current != _file_record(source):
        raise SystemExit(f"[agent_sync] 旧命令账本无摘要且目标与源不一致，冲突：{path}")


def sync_file_commands(plan: Plan, rel: str, enabled: bool = True) -> list:
    destination = plan.root / rel
    marker = destination / GENERATED_FILE
    previous = _command_ledger(marker) if marker.is_file() else {}
    commands = _command_files(plan.root) if enabled else []
    wanted = {command.name for command in commands}
    sources = {command.name: command for command in commands}
    for name, old_record in sorted(previous.items()):
        target = destination / name
        if os.path.lexists(target):
            _check_command(plan.root, target, old_record, sources.get(name))
        elif name not in wanted:
            raise SystemExit(f"[agent_sync] 受管命令缺失，冲突：{target}")
    for name in sorted(previous.keys() - wanted):
        plan.remove(destination / name, "command source removed")
    generated = []
    for command in commands:
        target = destination / command.name
        if (target.exists() or target.is_symlink()) and command.name not in previous:
            if not _is_generated(target, plan.root):
                raise SystemExit(f"[agent_sync] 原生命令目标已存在用户内容，拒绝覆盖：{target}")
            _check_command(plan.root, target, None, command)
        plan.link_file(target, command)
        generated.append(f"{rel}/{command.name}")
    if wanted:
        records = {name: _file_record(destination / name) if plan.apply
                   else _file_record(sources[name]) for name in sorted(wanted)}
        plan.write_text(marker, json.dumps({"schema": "aidp.commands/v1", "files": records},
                                           ensure_ascii=False, sort_keys=True) + "\n")
        generated.append(f"{rel}/{GENERATED_FILE}")
    elif marker.is_file():
        plan.remove(marker, "no generated commands")
    return generated


def sync_codex_commands(plan: Plan) -> list:
    destination = plan.root / CODEX_COMMAND_SKILLS
    wanted = set()
    generated = []
    for command in _command_files(plan.root):
        name = command.stem
        target = destination / name
        _require_generated_or_absent(plan.root, target, "Codex 命令 SKILL")
        wanted.add(name)
        plan.write_text(target / "SKILL.md", codex_command_skill(name, _read(command)))
        plan.write_text(target / "agents/openai.yaml", OPENAI_YAML)
        if plan.apply:
            marker = _directory_marker(target)
        else:
            marker = _read(target / GENERATED_FILE) or "native-command\n"
        plan.write_text(target / GENERATED_FILE, marker)
        generated.append(f"{CODEX_COMMAND_SKILLS}/{name}")
    _prune(plan, destination, wanted)
    return generated


def _covered_by_dir_rules(text_outside: str, entry: str) -> bool:
    """entry（仓库相对路径）是否已被块外的锚定目录规则（如 `/.claude/`）整体忽略。"""
    for line in text_outside.splitlines():
        rule = line.strip()
        if not rule or rule.startswith(("#", "!")) or not rule.endswith("/") or any(c in rule for c in "*?["):
            continue
        prefix = rule.lstrip("/")
        if entry == prefix.rstrip("/") or entry.startswith(prefix):
            return True
    return False


def sync_gitignore(plan: Plan, generated: list):
    """根 .gitignore 托管块：列出全部生成物（块外目录规则已覆盖的不重复登记）；块外内容原样保留。"""
    path = plan.root / ".gitignore"
    text = _read(path)
    block_re = re.compile(re.escape(GITIGNORE_BEGIN) + r".*?" + re.escape(GITIGNORE_END) + r"\n?", re.S)
    outside = block_re.sub("", text)
    generated = [g for g in generated if not _covered_by_dir_rules(outside, g)]
    body = "".join(f"/{g}\n" for g in sorted(set(generated)))
    block = f"{GITIGNORE_BEGIN}\n{body}{GITIGNORE_END}\n" if generated else ""
    if block_re.search(text):
        new = block_re.sub(lambda _m: block, text)
        if not block:
            new = new.rstrip("\n") + "\n" if new.strip() else ""
    elif block:
        new = (text.rstrip("\n") + "\n\n" if text.strip() else "") + block
    else:
        new = text
    if new != text:
        plan.write_text(path, new)


# ── 插件（`AIDP_HOME/plugins/<name>/`：随仓库分发，含 MCP 声明与配套 SKILL）──────────
def _plugin_dirs(root: Path) -> list:
    base = RUNTIME_ROOT / PLUGINS_SRC
    if not base.is_dir():
        return []
    return sorted(p for p in base.iterdir()
                  if p.is_dir() and ((p / ".claude-plugin" / "plugin.json").is_file()
                                     or (p / "plugin.json").is_file()))


def _validate_copy_sources(root: Path, plugins: list):
    for command in _command_files(root):
        _validate_material_path(root, command, expect_dir=False)
    for skill in _base_skill_dirs(root).values():
        _validate_material_path(root, skill, expect_dir=True)
    for plugin in plugins:
        _validate_material_path(root, plugin, expect_dir=True)
    if STOP_GUARD_SOURCE.exists() or STOP_GUARD_SOURCE.is_symlink():
        _validate_material_path(root, STOP_GUARD_SOURCE, expect_dir=False)


def _plugin_manifest(pdir: Path) -> dict:
    for rel in (".claude-plugin/plugin.json", "plugin.json"):
        try:
            return json.loads(_read(pdir / rel) or "{}")
        except json.JSONDecodeError:
            raise SystemExit(f"[agent_sync] {pdir / rel} 不是合法 JSON")
    return {}


def _plugin_mcp(pdir: Path, manifest: dict) -> dict:
    """插件声明的 MCP servers：根 `.mcp.json` / `mcp.json` 优先，其次 manifest 内联。"""
    for rel in (".mcp.json", "mcp.json"):
        if (pdir / rel).is_file():
            try:
                return (json.loads(_read(pdir / rel)) or {}).get("mcpServers") or {}
            except json.JSONDecodeError:
                raise SystemExit(f"[agent_sync] {pdir / rel} 不是合法 JSON")
    return manifest.get("mcpServers") or {}


def sync_claude_plugins(plan: Plan, plugins: list) -> list:
    """Claude Code 项目插件；settings 只增删 marker 明确记录的键。"""
    root, generated = plan.root, []
    for plugin in plugins:
        name = plugin.name
        plan.link_dir(root / CLAUDE_PLUGINS / name, plugin)
        generated.append(f"{CLAUDE_PLUGINS}/{name}")
    _prune(plan, root / CLAUDE_PLUGINS, {plugin.name for plugin in plugins})

    path = root / ".claude/settings.json"
    marker = root / CLAUDE_PLUGIN_MANAGED
    if not plugins and not marker.is_file():
        return generated
    try:
        data = json.loads(_read(path) or "{}")
        previous = json.loads(_read(marker) or "{}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"[agent_sync] Claude 插件配置不是合法 JSON：{exc}")
    markets = data.setdefault("extraKnownMarketplaces", {})
    enabled = data.setdefault("enabledPlugins", {})
    for key in previous.get("marketplaces", []):
        markets.pop(key, None)
    for key in previous.get("enabledPlugins", []):
        enabled.pop(key, None)

    managed_markets = []
    managed_enabled = []
    for plugin in plugins:
        marketplace_file = plugin / ".claude-plugin/marketplace.json"
        marketplace = json.loads(_read(marketplace_file) or "{}") if marketplace_file.is_file() else {}
        market = marketplace.get("name") or f"{plugin.name}-marketplace"
        desired_market = {"source": {"source": "directory", "path": f"./{CLAUDE_PLUGINS}/{plugin.name}"}}
        if market in markets and markets[market] != desired_market:
            raise SystemExit(f"[agent_sync] Claude marketplace 用户配置冲突：{market}")
        if market not in markets:
            markets[market] = desired_market
            managed_markets.append(market)
        for entry in marketplace.get("plugins") or [{"name": plugin.name}]:
            key = f"{entry.get('name', plugin.name)}@{market}"
            if key in enabled and enabled[key] is not True:
                raise SystemExit(f"[agent_sync] Claude enabledPlugins 用户配置冲突：{key}")
            if key not in enabled:
                enabled[key] = True
                managed_enabled.append(key)

    if not markets:
        data.pop("extraKnownMarketplaces", None)
    if not enabled:
        data.pop("enabledPlugins", None)
    plan.write_text(path, _json_dump(data))
    managed = {"marketplaces": managed_markets, "enabledPlugins": managed_enabled}
    if managed_markets or managed_enabled:
        plan.write_text(marker, _json_dump(managed))
        generated.append(CLAUDE_PLUGIN_MANAGED)
    elif marker.is_file():
        plan.remove(marker, "no managed Claude plugin settings")
    return generated


def _plugin_skill_dirs(plugins: list) -> dict:
    """递归发现插件 SKILL；冲突键优先使用 frontmatter `name`。"""
    result = {}
    for plugin in plugins:
        source = plugin / "skills"
        if not source.is_dir():
            continue
        for skill_file in sorted(list(source.rglob("SKILL.md"))
                                 + list(source.rglob("SKILL.md.in"))):
            if skill_file.is_symlink() or not skill_file.is_file():
                continue
            skill = skill_file.parent
            name = _frontmatter(_read(skill_file)).get("name") or skill.name
            if name in result:
                first = result[name]
                raise SystemExit(
                    f"[agent_sync] 插件 SKILL 重名冲突：{name}；来源：{first}；{skill}")
            result[name] = skill
    return result


def _plugin_servers(plugins: list) -> dict:
    servers = {}
    for plugin in plugins:
        for name, config in _plugin_mcp(plugin, _plugin_manifest(plugin)).items():
            if name in servers and servers[name] != config:
                raise SystemExit(f"[agent_sync] 插件 MCP server 重名冲突：{name}")
            servers[name] = config
    return servers


def sync_codex_plugin_skills(plan: Plan, plugins: list) -> list:
    """只用于清理旧 Codex 专属插件入口；新入口统一位于 `.agents/skills`。"""
    base = plan.root / CODEX_PLUGIN_SKILLS
    for plugin in plugins:
        target = base / plugin.name
        if _is_generated(target, plan.root):
            plan.remove(target, "legacy Codex plugin skills")
    _prune(plan, base, {"aidp"})
    return []


def sync_shared_plugin_skills(plan: Plan, plugins: list, enabled: bool = True) -> list:
    base = plan.root / SHARED_SKILLS
    wanted = set()
    generated = []
    for plugin in plugins if enabled else []:
        source = plugin / "skills"
        if not source.is_dir():
            continue
        wanted.add(plugin.name)
        target = base / plugin.name
        _require_generated_or_absent(plan.root, target, "共享插件 SKILL namespace")
        plan.link_dir(target / "skills", source)
        marker = _directory_marker(target) if plan.apply else (_read(target / GENERATED_FILE) or "plugin-skills\n")
        plan.write_text(target / GENERATED_FILE, marker)
        generated.append(f"{SHARED_SKILLS}/{plugin.name}")
    for plugin in plugins:
        if plugin.name not in wanted:
            target = base / plugin.name
            if _is_generated(target, plan.root):
                plan.remove(target, "plugin skills disabled")
    return generated


def _toml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_value(item) for item in value) + "]"
    return json.dumps(str(value), ensure_ascii=False)


def _codex_mcp_block(name: str, config: dict) -> str:
    lines = [CODEX_MCP_BEGIN.format(name=name), f"[mcp_servers.{name}]"]
    for key in ("command", "args", "url", "enabled", "startup_timeout_sec", "tool_timeout_sec"):
        if key in config:
            lines.append(f"{key} = {_toml_value(config[key])}")
    lines.append(CODEX_MCP_END.format(name=name))
    return "\n".join(lines) + "\n"


def _toml_scalar(raw: str):
    raw = raw.strip()
    try:
        return json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        return raw.strip('"').strip("'")


def _toml_section(text: str, header: str):
    match = re.search(rf"(?m)^\[{re.escape(header)}\]\s*$", text)
    if not match:
        return None
    next_header = re.search(r"(?m)^\[", text[match.end():])
    end = match.end() + next_header.start() if next_header else len(text)
    values = {}
    for line in text[match.end():end].splitlines():
        item = re.match(r"^\s*([A-Za-z0-9_-]+)\s*=\s*(.*?)\s*$", line)
        if item:
            values[item.group(1)] = _toml_scalar(item.group(2))
    return values


def _mcp_matches(existing: dict, desired: dict) -> bool:
    return all(existing.get(key) == value for key, value in desired.items())


def _without_codex_managed_mcp(text: str) -> str:
    return re.sub(r"(?ms)^# >>> AIDP-MCP [^\n]+ >>>\n.*?^# <<< AIDP-MCP [^\n]+ <<<\n?", "", text)


def _validate_codex_mcp(root: Path, servers: dict):
    text = _without_codex_managed_mcp(_read(root / ".codex/config.toml"))
    for name, config in sorted(servers.items()):
        if not isinstance(config, dict):
            raise SystemExit(f"[agent_sync] Codex MCP server {name} 配置必须是对象")
        unsupported = sorted(set(config) - CODEX_MCP_SUPPORTED_FIELDS)
        if unsupported:
            raise SystemExit(
                f"[agent_sync] Codex MCP server {name} 含未支持字段：{', '.join(unsupported)}")
        existing = _toml_section(text, f"mcp_servers.{name}")
        if existing is not None and not _mcp_matches(existing, config):
            raise SystemExit(f"[agent_sync] Codex 未受管 MCP server 配置冲突：{name}")


def sync_codex_mcp(plan: Plan, servers: dict, legacy_plugins: set):
    path = plan.root / ".codex/config.toml"
    original = _read(path)
    text = _without_codex_managed_mcp(original)
    for plugin_name in sorted(legacy_plugins):
        pattern = (rf'(?ms)^\[plugins\."{re.escape(plugin_name)}@local-repo"\]\s*\n'
                   r'.*?(?=^\[|\Z)')
        text = re.sub(pattern, "", text)

    managed_servers = {}
    for name, config in sorted(servers.items()):
        existing = _toml_section(text, f"mcp_servers.{name}")
        if existing is None:
            managed_servers[name] = config
        elif not _mcp_matches(existing, config):
            raise SystemExit(f"[agent_sync] Codex 未受管 MCP server 配置冲突：{name}")

    text = text.rstrip()
    blocks = "\n".join(_codex_mcp_block(name, config).rstrip()
                       for name, config in sorted(managed_servers.items()))
    if blocks:
        text = (text + "\n\n" if text else "") + blocks + "\n"
    elif text:
        text += "\n"
    if text != original:
        plan.write_text(path, text)


def _validate_dsh_mcp(root: Path, servers: dict):
    path = root / ".dsh/mcp.json"
    try:
        data = json.loads(_read(path) or "{}")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] {path} 不是合法 JSON，拒绝覆盖，请先修复")
    current = data.get("mcpServers") or {}
    if not isinstance(current, dict):
        raise SystemExit(f"[agent_sync] {path} 的 mcpServers 必须是对象")
    previous = _generated_names(root / DSH_MCP_MANAGED)
    for name, config in servers.items():
        if name in current and name not in previous and current[name] != config:
            raise SystemExit(f"[agent_sync] DSH 未受管 MCP server 配置冲突：{name}")


def sync_dsh_mcp(plan: Plan, servers: dict) -> list:
    root = plan.root
    path = root / ".dsh/mcp.json"
    marker = root / DSH_MCP_MANAGED
    try:
        data = json.loads(_read(path) or "{}")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] {path} 不是合法 JSON，拒绝覆盖，请先修复")
    current = data.get("mcpServers")
    if current is None:
        current = {}
    if not isinstance(current, dict):
        raise SystemExit(f"[agent_sync] {path} 的 mcpServers 必须是对象")

    previous = _generated_names(marker)
    for name in previous:
        current.pop(name, None)
    managed = set()
    for name, config in sorted(servers.items()):
        if name in current:
            if current[name] != config:
                raise SystemExit(f"[agent_sync] DSH 未受管 MCP server 配置冲突：{name}")
            continue
        current[name] = config
        managed.add(name)

    if current:
        data["mcpServers"] = current
    else:
        data.pop("mcpServers", None)
    generated = []
    if data:
        plan.write_text(path, _json_dump(data))
        generated.append(".dsh/mcp.json")
    elif path.is_file():
        plan.remove(path, "no DSH MCP configuration remains")
    if managed:
        plan.write_text(marker, json.dumps(sorted(managed), ensure_ascii=False) + "\n")
        generated.append(DSH_MCP_MANAGED)
    elif marker.is_file():
        plan.remove(marker, "no managed DSH MCP servers")
    return generated


def _legacy_codex_managed(root: Path) -> set:
    base = root / LEGACY_CODEX_PLUGINS
    managed = {path.name for path in base.iterdir()
               if path.is_dir() and (path / GENERATED_FILE).is_file()} if base.is_dir() else set()
    marker = base / GENERATED_FILE
    if _read(marker) == "marketplace\n":
        try:
            marketplace = json.loads(_read(base / "marketplace.json") or "{}")
        except json.JSONDecodeError:
            marketplace = {}
        managed.update(entry.get("name") for entry in marketplace.get("plugins", [])
                       if isinstance(entry, dict) and entry.get("name"))
    return managed


def cleanup_legacy_codex_plugins(plan: Plan) -> set:
    base = plan.root / LEGACY_CODEX_PLUGINS
    managed = _legacy_codex_managed(plan.root)
    marker = base / GENERATED_FILE
    _prune(plan, base, set())
    if _read(marker) == "marketplace\n":
        plan.remove(marker, "legacy marketplace marker")
    return managed


# ── hooks ────────────────────────────────────────────────────────────────────
def _hook_rel(agent: str) -> str:
    return f"{AGENT_RUNTIME_HOME[agent]}/hooks/autopilot-stop-guard.py"


def _hook_cmd(agent: str) -> str:
    rel = _hook_rel(agent)
    if agent == "claude":
        return f'python3 "$CLAUDE_PROJECT_DIR/{rel}"'
    return f'python3 "${{PWD}}/{rel}" --agent {agent}'


def _is_managed_stop_hook(command: str, root: Path | None = None) -> bool:
    try:
        argv = shlex.split(command)
    except ValueError:
        return False
    if len(argv) not in (2, 4) or argv[0] != "python3":
        return False
    if len(argv) == 4 and (argv[2] != "--agent" or argv[3] not in ("codex", "dsh")):
        return False
    legacy = f"{LEGACY_AIDP_DIR}/hooks/autopilot-stop-guard.py"
    claude = _hook_rel("claude")
    shared = _hook_rel("codex")
    rel_paths = (legacy, claude, shared)
    path = argv[1]
    if path in rel_paths:
        return True
    if path in (f"$CLAUDE_PROJECT_DIR/{rel}" for rel in (legacy, claude)):
        return True
    if path in (f"${{PWD}}/{rel}" for rel in (legacy, shared)):
        return True
    return bool(root and Path(path).is_absolute()
                and any(_lexical(Path(path)) == _lexical(root / rel) for rel in rel_paths))


def _merge_stop_hook(data: dict, cmd: str, root: Path | None = None) -> dict:
    hooks = data.setdefault("hooks", {})
    stop = hooks.setdefault("Stop", [])
    for group in stop:
        for h in group.get("hooks", []):
            if _is_managed_stop_hook(h.get("command", ""), root):
                h["command"] = cmd
                h["type"] = "command"
                return data
    stop.append({"hooks": [{"type": "command", "command": cmd}]})
    return data


def _json_dump(data: dict) -> str:
    return json.dumps(data, ensure_ascii=False, indent=2) + "\n"


def sync_hooks(plan: Plan, agent: str):
    root = plan.root
    if not STOP_GUARD_SOURCE.is_file():
        return
    path = {"claude": root / ".claude" / "settings.json",
            "codex": root / ".codex" / "hooks.json",
            "dsh": root / ".dsh" / "hooks.json"}[agent]
    try:
        data = json.loads(_read(path) or "{}")
    except json.JSONDecodeError:
        raise SystemExit(f"[agent_sync] {path} 不是合法 JSON，拒绝覆盖，请先修复")
    plan.write_text(path, _json_dump(_merge_stop_hook(data, _hook_cmd(agent), root)))
    if agent == "codex":
        cfg = root / ".codex" / "config.toml"
        text = _read(cfg)
        merged = _merge_codex_hook_flag(text)
        if merged != text:
            plan.write_text(cfg, merged)


# ── 主流程 ────────────────────────────────────────────────────────────────────
def _declared_skill_names(skills: dict) -> set:
    return {_frontmatter(_read(_skill_entry(path) or path / "SKILL.md")).get("name") or path.name
            for path in skills.values()}


def _name_conflicts(root: Path, plugin_skills: dict) -> list:
    skills = _declared_skill_names(_base_skill_dirs(root)) | set(plugin_skills)
    commands = {path.stem for path in _command_files(root)}
    return sorted(skills & commands)


def _json_object(path: Path, label: str) -> dict:
    try:
        value = json.loads(_read(path) or "{}")
    except json.JSONDecodeError as exc:
        raise SystemExit(f"[agent_sync] {label} JSON 非法：{exc}")
    if not isinstance(value, dict):
        raise SystemExit(f"[agent_sync] {label} 类型错误：顶层必须是对象")
    return value


def _validate_hook_structure(data: dict, path: Path):
    hooks = data.get("hooks", {})
    if not isinstance(hooks, dict):
        raise SystemExit(f"[agent_sync] hooks 结构错误：{path} 的 hooks 必须是对象")
    stop = hooks.get("Stop", [])
    if not isinstance(stop, list):
        raise SystemExit(f"[agent_sync] hooks 结构错误：{path} 的 Stop 必须是数组")
    for index, group in enumerate(stop):
        if not isinstance(group, dict):
            raise SystemExit(f"[agent_sync] hooks 结构错误：{path} Stop[{index}] 必须是对象")
        entries = group.get("hooks", [])
        if not isinstance(entries, list):
            raise SystemExit(f"[agent_sync] hooks 结构错误：{path} Stop[{index}].hooks 必须是数组")
        for hook_index, hook in enumerate(entries):
            if not isinstance(hook, dict):
                raise SystemExit(
                    f"[agent_sync] hooks 结构错误：{path} Stop[{index}].hooks[{hook_index}] 必须是对象")
            if "command" in hook and not isinstance(hook["command"], str):
                raise SystemExit(f"[agent_sync] hooks 结构错误：{path} command 必须是字符串")
            if "type" in hook and not isinstance(hook["type"], str):
                raise SystemExit(f"[agent_sync] hooks 结构错误：{path} type 必须是字符串")


def _validate_codex_features(root: Path):
    path = root / ".codex/config.toml"
    text = _read(path)
    feature_headers = list(re.finditer(r"(?m)^[ \t]*\[features\][ \t]*$", text))
    assignments = list(re.finditer(r"(?m)^[ \t]*codex_hooks[ \t]*=.*$", text))
    hook_keys = list(CODEX_HOOK_LINE_RE.finditer(text))
    if len(feature_headers) > 1:
        raise SystemExit(f"[agent_sync] Codex features 结构错误：{path} 含重复 [features] section")
    if len(assignments) > 1:
        raise SystemExit(f"[agent_sync] Codex features 结构错误：{path} 含重复 codex_hooks 键")
    if assignments and not hook_keys:
        raise SystemExit(f"[agent_sync] Codex features 结构错误：codex_hooks 必须是 true/false")
    if hook_keys:
        if not feature_headers:
            raise SystemExit(f"[agent_sync] Codex features 结构错误：codex_hooks 不在 [features] section")
        start = feature_headers[0].end()
        next_header = re.search(r"(?m)^[ \t]*\[", text[start:])
        end = start + next_header.start() if next_header else len(text)
        if not (start <= hook_keys[0].start() < end):
            raise SystemExit(f"[agent_sync] Codex features 结构错误：codex_hooks 不在 [features] section")


def _merge_codex_hook_flag(text: str) -> str:
    if CODEX_HOOK_LINE_RE.search(text):
        def replace(match):
            return (f"{match.group('indent')}codex_hooks{match.group('before')}="
                    f"{match.group('after')}true{match.group('comment')}")
        return CODEX_HOOK_LINE_RE.sub(replace, text, count=1)
    if re.search(r"(?m)^[ \t]*\[features\][ \t]*$", text):
        return re.sub(r"(?m)^([ \t]*\[features\][ \t]*)$", r"\1\ncodex_hooks = true", text, count=1)
    return (text.rstrip() + "\n\n" if text.strip() else "") + "[features]\ncodex_hooks = true\n"


def _validate_hooks(root: Path, agents: list):
    if not STOP_GUARD_SOURCE.is_file():
        return
    paths = {"claude": root / ".claude/settings.json",
             "codex": root / ".codex/hooks.json",
             "dsh": root / ".dsh/hooks.json"}
    for agent in agents:
        path = paths[agent]
        data = _json_object(path, f"{agent} hooks {path}") if path.exists() else {}
        _validate_hook_structure(data, path)
        _merge_stop_hook(json.loads(json.dumps(data)), _hook_cmd(agent), root)
    if "codex" in agents:
        _validate_codex_features(root)


def _validate_claude_plugins(root: Path, plugins: list):
    marker_path = root / CLAUDE_PLUGIN_MANAGED
    settings_path = root / ".claude/settings.json"
    if not plugins and not marker_path.is_file():
        return
    settings = _json_object(settings_path, "Claude settings")
    marker = _json_object(marker_path, "Claude plugin marker") if marker_path.is_file() else {}
    for field in ("marketplaces", "enabledPlugins"):
        values = marker.get(field, [])
        if not isinstance(values, list) or any(not isinstance(item, str) for item in values):
            raise SystemExit(f"[agent_sync] Claude plugin marker 字段类型错误：{field}")
    markets = settings.get("extraKnownMarketplaces", {})
    enabled = settings.get("enabledPlugins", {})
    if not isinstance(markets, dict):
        raise SystemExit("[agent_sync] Claude settings 字段类型错误：extraKnownMarketplaces 必须是对象")
    if not isinstance(enabled, dict):
        raise SystemExit("[agent_sync] Claude settings 字段类型错误：enabledPlugins 必须是对象")
    markets = dict(markets)
    enabled = dict(enabled)
    for key in marker.get("marketplaces", []):
        markets.pop(key, None)
    for key in marker.get("enabledPlugins", []):
        enabled.pop(key, None)

    for plugin in plugins:
        marketplace_path = plugin / ".claude-plugin/marketplace.json"
        marketplace = _json_object(marketplace_path, f"Claude marketplace {marketplace_path}") \
            if marketplace_path.is_file() else {}
        name = marketplace.get("name") or f"{plugin.name}-marketplace"
        entries = marketplace.get("plugins", [{"name": plugin.name}])
        if not isinstance(name, str) or not isinstance(entries, list) \
                or any(not isinstance(entry, dict) for entry in entries):
            raise SystemExit(f"[agent_sync] Claude marketplace 字段类型错误：{marketplace_path}")
        desired = {"source": {"source": "directory", "path": f"./{CLAUDE_PLUGINS}/{plugin.name}"}}
        if name in markets and markets[name] != desired:
            raise SystemExit(f"[agent_sync] Claude marketplace 用户配置冲突：{name}")
        for entry in entries:
            plugin_name = entry.get("name", plugin.name)
            if not isinstance(plugin_name, str):
                raise SystemExit(f"[agent_sync] Claude marketplace 字段类型错误：{marketplace_path}")
            key = f"{plugin_name}@{name}"
            if key in enabled and enabled[key] is not True:
                raise SystemExit(f"[agent_sync] Claude enabledPlugins 用户配置冲突：{key}")


def _validate_real_namespace(root: Path, rel: str, label: str):
    current = root
    for part in Path(rel).parts:
        current = current / part
        if current.is_symlink():
            raise SystemExit(f"[agent_sync] {label} 必须位于真实目录，拒绝 symlink：{current}")
        if current.exists() and not current.is_dir():
            raise SystemExit(f"[agent_sync] {label} 必须位于真实目录，发现非目录：{current}")


def _validate_adapter_namespaces(root: Path, plugins: list):
    namespaces = {
        ".claude", CLAUDE_SKILLS, CLAUDE_COMMANDS, CLAUDE_PLUGINS,
        ".codex", CODEX_PLUGIN_SKILLS, CODEX_COMMAND_SKILLS,
        ".dsh", DSH_COMMANDS, ".dsh/skills",
        ".agents", SHARED_SKILLS, LEGACY_CODEX_PLUGINS,
    }
    namespaces.update(f"{SHARED_SKILLS}/{plugin.name}" for plugin in plugins
                      if (plugin / "skills").is_dir())
    for rel in sorted(namespaces, key=lambda item: (len(Path(item).parts), item)):
        _validate_real_namespace(root, rel, f"Agent 适配 namespace {rel}")


def _has_managed_marker(path: Path) -> bool:
    try:
        return (path / GENERATED_FILE).is_file()
    except OSError as exc:
        raise SystemExit(f"[agent_sync] 受管目录无法检查，冲突：{path}：{exc}") from exc


def _validate_existing_managed(root: Path, agents: list, plugins: list):
    skills = _base_skill_dirs(root)
    for rel in (CLAUDE_SKILLS, SHARED_SKILLS):
        base = root / rel
        if not base.is_dir() or base.is_symlink():
            continue
        for target in base.iterdir():
            if target.is_symlink() or not _has_managed_marker(target):
                continue
            source = skills.get(target.name)
            plugin = next((item for item in plugins if item.name == target.name), None)
            if plugin is not None and rel == SHARED_SKILLS and (plugin / "skills").is_dir():
                source = plugin / "skills"
                if _read(target / GENERATED_FILE) == "plugin-skills\n":
                    if not _tree_equal(source, target / "skills"):
                        raise SystemExit(f"[agent_sync] 旧插件目录被修改，冲突：{target}")
                    continue
                if (target / "skills" / GENERATED_FILE).is_file():
                    _check_managed_directory(target / "skills", source)
                source = None
            if source is None and _read(target / GENERATED_FILE) == "directory-copy\n":
                raise SystemExit(f"[agent_sync] 旧受管目录源已删除，无法验证，冲突：{target}")
            _check_managed_directory(target, source)
    plugin_by_name = {plugin.name: plugin for plugin in plugins}
    for rel, sources in ((CLAUDE_PLUGINS, plugin_by_name),):
        base = root / rel
        if base.is_dir() and not base.is_symlink():
            for target in base.iterdir():
                if target.is_dir() and not target.is_symlink() and _has_managed_marker(target):
                    _check_managed_directory(target, sources.get(target.name))
    for rel in (CLAUDE_COMMANDS, DSH_COMMANDS):
        base = root / rel
        marker = base / GENERATED_FILE
        if not marker.is_file():
            continue
        ledger = _command_ledger(marker)
        sources = {command.name: command for command in _command_files(root)}
        for name, record in ledger.items():
            target = base / name
            if os.path.lexists(target):
                _check_command(root, target, record, sources.get(name))
            elif name not in sources:
                raise SystemExit(f"[agent_sync] 受管命令缺失，冲突：{target}")
    base = root / CODEX_COMMAND_SKILLS
    if base.is_dir() and not base.is_symlink():
        sources = {command.stem: command for command in _command_files(root)}
        for target in base.iterdir():
            if not target.is_dir() or target.is_symlink() or not _has_managed_marker(target):
                continue
            marker = _read(target / GENERATED_FILE)
            if marker == "native-command\n":
                command = sources.get(target.name)
                if command is None or _read(target / "SKILL.md") != codex_command_skill(target.name, _read(command)) \
                        or _read(target / "agents/openai.yaml") != OPENAI_YAML \
                        or any(p.relative_to(target).as_posix() not in
                               {GENERATED_FILE, "SKILL.md", "agents", "agents/openai.yaml"}
                               for p in target.rglob("*")):
                    raise SystemExit(f"[agent_sync] 旧 Codex 命令被修改，冲突：{target}")
            else:
                _check_managed_directory(target)


def _validate_targets(root: Path, agents: list, plugins: list, plugin_skills: dict):
    if "claude" in agents:
        for name in _base_skill_dirs(root):
            _require_generated_or_absent(root, root / CLAUDE_SKILLS / name, "Claude SKILL 入口")
        destination = root / CLAUDE_COMMANDS
        previous = _generated_names(destination / GENERATED_FILE)
        for command in _command_files(root):
            target = destination / command.name
            if (target.exists() or target.is_symlink()) and command.name not in previous:
                if not _is_generated(target, root):
                    raise SystemExit(f"[agent_sync] Claude 命令目标已存在用户内容，拒绝覆盖：{target}")
                _check_command(root, target, None, command)
        for plugin in plugins:
            _require_generated_or_absent(root, root / CLAUDE_PLUGINS / plugin.name,
                                         "Claude 插件目录")
    if "codex" in agents:
        for command in _command_files(root):
            _require_generated_or_absent(root, root / CODEX_COMMAND_SKILLS / command.stem,
                                         "Codex 命令 SKILL")
    if "dsh" in agents:
        destination = root / DSH_COMMANDS
        previous = _generated_names(destination / GENERATED_FILE)
        for command in _command_files(root):
            target = destination / command.name
            if (target.exists() or target.is_symlink()) and command.name not in previous:
                if not _is_generated(target, root):
                    raise SystemExit(f"[agent_sync] 原生命令目标已存在用户内容，拒绝覆盖：{target}")
                _check_command(root, target, None, command)
    if "codex" in agents or "dsh" in agents:
        for name in _base_skill_dirs(root):
            _require_generated_or_absent(root, root / SHARED_SKILLS / name, "SKILL 入口")
        for plugin in plugins:
            if (plugin / "skills").is_dir():
                _require_generated_or_absent(root, root / SHARED_SKILLS / plugin.name,
                                             "共享插件 SKILL namespace")


def run(root: Path, agents: list, mode: str, apply: bool) -> dict:
    global RUNTIME_ROOT
    shared_runtime = RUNTIME_ROOT
    claude_runtime = root / AGENT_RUNTIME_HOME["claude"]
    if not (claude_runtime / ".aidp-runtime.json").is_file():
        claude_runtime = shared_runtime
    plugins = _plugin_dirs(root)
    _validate_copy_sources(root, plugins)
    if "claude" in agents and claude_runtime != shared_runtime:
        RUNTIME_ROOT = claude_runtime
        try:
            claude_plugins = _plugin_dirs(root)
            _validate_copy_sources(root, claude_plugins)
        finally:
            RUNTIME_ROOT = shared_runtime
    else:
        claude_plugins = plugins
    plugin_skills = _plugin_skill_dirs(plugins) if ({"codex", "dsh"} & set(agents)) else {}
    public_skill_dirs = _base_skill_dirs(root)
    public_skills = _declared_skill_names(public_skill_dirs)
    plugins_with_skills = {plugin.name: plugin for plugin in plugins
                           if (plugin / "skills").is_dir()}
    path_clash = sorted(set(public_skill_dirs) & set(plugins_with_skills))
    if path_clash:
        details = "; ".join(
            f"{name}：{public_skill_dirs[name]}；{plugins_with_skills[name]}"
            for name in path_clash)
        raise SystemExit(f"[agent_sync] 共享 SKILL namespace 冲突：{details}")
    skill_clash = sorted(public_skills & set(plugin_skills))
    declared_namespace_clash = sorted(public_skills & set(plugins_with_skills))
    if skill_clash or declared_namespace_clash:
        names = sorted(set(skill_clash) | set(declared_namespace_clash))
        raise SystemExit(f"[agent_sync] 插件 SKILL 与公共 SKILL 同名冲突：{', '.join(names)}")
    clash = _name_conflicts(root, plugin_skills)
    if clash:
        raise SystemExit(f"[agent_sync] 命令与 SKILL 同名冲突：{', '.join(clash)}，请改名其一")
    all_servers = _plugin_servers(plugins)
    _validate_adapter_namespaces(root, plugins)
    _validate_existing_managed(root, agents, plugins)
    _validate_targets(root, agents, plugins, plugin_skills)
    if "claude" in agents and claude_runtime != shared_runtime:
        RUNTIME_ROOT = claude_runtime
        try:
            _validate_targets(root, ["claude"], claude_plugins, {})
        finally:
            RUNTIME_ROOT = shared_runtime
    _validate_hooks(root, agents)
    _validate_claude_plugins(root, claude_plugins if "claude" in agents else [])
    if "codex" in agents:
        _validate_codex_mcp(root, all_servers)
    if "dsh" in agents:
        _validate_dsh_mcp(root, all_servers)

    plan = Plan(root, apply, mode)
    sync_memory(plan, agents)
    for agent in agents:
        sync_hooks(plan, agent)
    legacy_plugins = cleanup_legacy_codex_plugins(plan)
    generated = []

    if "claude" in agents:
        RUNTIME_ROOT = claude_runtime
        try:
            generated += sync_skill_dir(plan, CLAUDE_SKILLS)
            generated += sync_file_commands(plan, CLAUDE_COMMANDS)
            generated += sync_claude_plugins(plan, claude_plugins)
        finally:
            RUNTIME_ROOT = shared_runtime
    else:
        _prune(plan, root / CLAUDE_SKILLS, set())
        sync_file_commands(plan, CLAUDE_COMMANDS, enabled=False)
        sync_claude_plugins(plan, [])

    shared_enabled = bool({"codex", "dsh"} & set(agents))
    plugin_names = {plugin.name for plugin in plugins if (plugin / "skills").is_dir()}
    if shared_enabled:
        generated += sync_skill_dir(plan, SHARED_SKILLS, preserve=plugin_names)
        generated += sync_shared_plugin_skills(plan, plugins)
    else:
        _prune(plan, root / SHARED_SKILLS, set())
        sync_shared_plugin_skills(plan, plugins, enabled=False)

    if "codex" in agents:
        generated += sync_codex_commands(plan)
        sync_codex_plugin_skills(plan, plugins)
        sync_codex_mcp(plan, all_servers, legacy_plugins)
    else:
        _prune(plan, root / CODEX_COMMAND_SKILLS, set())
        sync_codex_plugin_skills(plan, [])
        sync_codex_mcp(plan, {}, legacy_plugins)

    if "dsh" in agents:
        generated += sync_file_commands(plan, DSH_COMMANDS)
        generated += sync_dsh_mcp(plan, all_servers)
    else:
        sync_file_commands(plan, DSH_COMMANDS, enabled=False)
        generated += sync_dsh_mcp(plan, {})

    _prune(plan, root / LEGACY_CODEX_COMMAND_SKILLS, set())
    _prune(plan, root / ".dsh/skills", set())
    sync_gitignore(plan, generated)
    return {"agents": agents, "mode": "managed-copy", "applied": apply,
            "drift": plan.drift, "actions": plan.actions}


def _self_check() -> int:
    """黑盒验证原生运行包可独立生成三端 managed-copy 入口。"""
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        runtime = root / AGENT_RUNTIME_HOME["codex"]
        shutil.copytree(RUNTIME_ROOT, runtime,
                        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "tests"))
        (root / "CLAUDE.md").write_bytes("# 正文\n".encode("utf-8"))
        (root / ".gitignore").write_bytes(b"node_modules/\n")
        for directory in (".claude", ".codex", ".dsh"):
            (root / directory).mkdir()

        script = runtime / "scripts/agent_sync.py"
        env = dict(os.environ, AIDP_PROJECT_ROOT=str(root), AIDP_HOME=str(runtime))

        def invoke(*extra):
            cp = subprocess.run(
                [sys.executable, str(script), "--root", str(root),
                 "--agents", "claude,codex,dsh", *extra],
                capture_output=True, text=True, env=env, timeout=60,
            )
            try:
                payload = json.loads(cp.stdout.strip().splitlines()[-1])
            except (ValueError, IndexError):
                payload = {}
            return cp.returncode, payload

        command = next((p.stem for p in sorted((runtime / "commands").glob("*.md"))
                        if p.stem.upper() != "README"), "")
        skill = next((p.name for p in sorted((runtime / "skills").iterdir())
                      if p.name != "aidp-code-engineer" and (p / "SKILL.md").is_file()), "")
        plugin = next((p for p in sorted((runtime / "plugins").iterdir())
                       if (p / "skills").is_dir()), None)
        plugin_skill = (next((p.name for p in sorted((plugin / "skills").iterdir())
                              if (p / "SKILL.md").is_file()), "") if plugin else "")

        first_rc, first = invoke("--mode", "link")
        check_rc, checked = invoke("--check")
        checks = {
            "first run": first_rc == 0 and first.get("drift") is True,
            "idempotent": check_rc == 0 and checked.get("drift") is False,
            "memory": _read(root / "AGENTS.md") == "# 正文\n" and _is_shell(_read(root / "CLAUDE.md")),
            "claude command": bool(command) and (root / CLAUDE_COMMANDS / f"{command}.md").is_file(),
            "codex command": bool(command) and (root / CODEX_COMMAND_SKILLS / command / "SKILL.md").is_file(),
            "dsh command": bool(command) and (root / DSH_COMMANDS / f"{command}.md").is_file(),
            "shared skill": bool(skill) and (root / SHARED_SKILLS / skill / "SKILL.md").is_file(),
            "no router": not (root / SHARED_SKILLS / OBSOLETE_ROUTER).exists(),
            "claude plugin": plugin is None or (root / CLAUDE_PLUGINS / plugin.name).is_dir(),
            "shared plugin skill": (plugin is None or not plugin_skill
                                    or (root / SHARED_SKILLS / plugin.name / "skills"
                                        / plugin_skill / "SKILL.md").is_file()),
            "no codex plugin duplicate": plugin is None or not (root / CODEX_PLUGIN_SKILLS / plugin.name).exists(),
            "hook": "codex_hooks = true" in _read(root / ".codex/config.toml"),
        }
        if command:
            (runtime / "commands" / f"{command}.md").unlink()
            checks["stale command detected"] = invoke("--check")[1].get("drift") is True
        bad = [name for name, passed in checks.items() if not passed]
        print(json.dumps({"self_check": "fail" if bad else "pass", "failed": bad}, ensure_ascii=False))
        return 1 if bad else 0


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--root", default=".")
    ap.add_argument("--agents", default="", help="逗号分隔：claude,codex,dsh；缺省按项目根目录检测")
    ap.add_argument("--mode", choices=("link", "copy"), default="copy")
    ap.add_argument("--check", action="store_true", help="只检查不写，有漂移 exit 1")
    ap.add_argument("--human", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args(argv)
    if a.self_check:
        return _self_check()
    root = Path(a.root).resolve()
    required = ("commands", "skills", "plugins", "scripts")
    missing = [name for name in required if not (RUNTIME_ROOT / name).is_dir()]
    if missing:
        print(json.dumps({"error": f"AIDP 运行包不完整：{','.join(missing)}"}, ensure_ascii=False))
        return 2
    if a.agents:
        agents = [x.strip() for x in a.agents.split(",") if x.strip()]
        unknown = [x for x in agents if x not in KNOWN_AGENTS]
        if unknown:
            print(json.dumps({"error": f"未知 Agent：{unknown}，可选 {list(KNOWN_AGENTS)}"}, ensure_ascii=False))
            return 2
    else:
        agents = detect_agents(root)
    try:
        result = run(root, agents, a.mode, apply=not a.check)
    except SystemExit as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False))
        return 2
    print(json.dumps(result, ensure_ascii=False))
    if a.human:
        for act in result["actions"]:
            print(f"  {act['op']:6} {act['path']}", file=sys.stderr)
    return 1 if (a.check and result["drift"]) else 0


if __name__ == "__main__":
    sys.exit(main())
